Repository abapGit/abapGit, pull requests merged in 2021-11, with the labels that each got.

#5087 Commit Page: Repo Header and Summary
  src/ui/zcl_abapgit_gui_page_commit.clas.abap
Labels: user interface

#5061 UI: Sticky Top
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
  src/ui/zabapgit_js_common.w3mi.data.js
  src/ui/zcl_abapgit_gui_page.clas.abap
Labels: user interface

#5093 SUSH: Fix check for lock
  src/objects/zcl_abapgit_object_sush.clas.abap
Labels: serialization

#5105 Docs: Update support for FTD0
  docs/ref-supported.md
Labels: documentation

#5106 WEBI: Fix changed_by, is_active, exists
  src/objects/zcl_abapgit_object_webi.clas.abap
Labels: serialization

#5113 Title case for hotkey descriptions
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/zcl_abapgit_gui_page_main.clas.abap
  src/ui/zcl_abapgit_gui_page_patch.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/zcl_abapgit_gui_page_sett_remo.clas.abap
Labels: user interface

#5114 Refactor: Jump to Object Logic
  src/objects/core/zcl_abapgit_gui_jumper.clas.abap
  src/objects/core/zcl_abapgit_gui_jumper.clas.xml
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/zcl_abapgit_ui_factory.clas.abap
  src/ui/zif_abapgit_gui_jumper.intf.abap
  src/ui/zif_abapgit_gui_jumper.intf.xml
  src/utils/zcl_abapgit_adt_link.clas.abap
Labels: refactoring

#5115 SHI3: Set buffer mode
  src/objects/zcl_abapgit_object_shi3.clas.abap
Labels: serialization

#5130 Update guide-changelog.md
  docs/collections/_development/guide-changelog.md
Labels: documentation

#5116 Make exceptions compatible with 702
  src/ui/core/zcx_abapgit_cancel.clas.abap
  src/zcx_abapgit_not_found.clas.abap
Labels: downport

#5129 Diff/Patch: Add "Filter by Object Type"
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
Labels: user interface

#5159 Repo View: Remove file path in folder view
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5160 Docs: Add i18n section to dev guidelines
  docs/collections/_development/guidelines.md
Labels: documentation

#4976 SRVB: Service Binding object changes
  src/objects/zcl_abapgit_object_srvb.clas.abap
Labels: serialization

#5168 Diff/Patch: Adjust view menu
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
Labels: user interface
