Repository abapGit/abapGit, pull requests merged in 2022-05, with the labels that each got.

#5507 DEVC: Clean-up OTR entries
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization

#5503 Remove "branch overview" class/interface
  src/zcl_abapgit_branch_overview.clas.abap
  src/zcl_abapgit_branch_overview.clas.testclasses.abap
  src/zcl_abapgit_branch_overview.clas.xml
  src/zcl_abapgit_factory.clas.abap
  src/zif_abapgit_branch_overview.intf.abap
  src/zif_abapgit_branch_overview.intf.xml
  src/zif_abapgit_definitions.intf.abap
Labels: refactoring

#5483 Refactor remote settings
  src/git_platform/zcl_abapgit_pr_enumerator.clas.abap
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/repo/zif_abapgit_repo_online.intf.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/zcl_abapgit_html_form.clas.abap
  src/ui/zif_abapgit_html_form.intf.abap
Labels: user interface

#5519 G4BA,G4BS: Clear/fill user and timestamp fields
  src/objects/zcl_abapgit_object_g4ba.clas.abap
  src/objects/zcl_abapgit_object_g4bs.clas.abap
Labels: bug, ci

#5521 SPRX: Add objects to transport
  src/objects/zcl_abapgit_object_sprx.clas.abap
Labels: bug, ci

#5490 WDYN: Add documentation and fix diffs
  src/objects/zcl_abapgit_object_wdyn.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: serialization, ci

#5518 OTGR: Fix errors with parent/child
  src/objects/zcl_abapgit_object_otgr.clas.abap
Labels: bug, ci

#5520 UENO: Clear/fill user, date, and time fields
  src/objects/zcl_abapgit_object_ueno.clas.abap
Labels: bug, ci

#5517 Fix "DB delete failed"
  src/persist/zcl_abapgit_persistence_db.clas.abap
Labels: bug, ci

#5508 Fix commit message encoding
  abaplint.json
  package.json
  src/ui/zcl_abapgit_html_action_utils.clas.abap
  src/ui/zcl_abapgit_html_action_utils.clas.testclasses.abap
Labels: bug

#5539 AMSD: Fix "Step DDIC is only for DDIC objects"
  src/objects/zcl_abapgit_object_amsd.clas.abap
Labels: serialization, bug, ci

#5540 UDMO: Fix wrong parameter value
  src/objects/zcl_abapgit_object_udmo.clas.abap
Labels: serialization

#5538 ENHC: Fix diffs due to OTR
  src/objects/zcl_abapgit_object_enhc.clas.abap
Labels: serialization, ci

#5486 DDIC: Improve active/inactive check
  src/objects/zcl_abapgit_object_doma.clas.abap
  src/objects/zcl_abapgit_object_dtel.clas.abap
  src/objects/zcl_abapgit_object_enqu.clas.abap
  src/objects/zcl_abapgit_object_shlp.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_ttyp.clas.abap
  src/objects/zcl_abapgit_object_type.clas.abap
  src/objects/zcl_abapgit_object_view.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: serialization

#5541 ASFC,SPLO,SPPF: Fix missing transport entry
  src/objects/zcl_abapgit_object_asfc.clas.abap
  src/objects/zcl_abapgit_object_splo.clas.abap
  src/objects/zcl_abapgit_object_sppf.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: serialization, ci

#5546 SHI3: Fix `exists` check
  src/objects/zcl_abapgit_object_shi3.clas.abap
Labels: serialization, bug, ci

#5545 IAxx: Fix locking of objects
  src/objects/zcl_abapgit_object_iarp.clas.abap
  src/objects/zcl_abapgit_object_iasp.clas.abap
  src/objects/zcl_abapgit_object_iatu.clas.abap
Labels: serialization, bug, ci

#5551 IOBJ/ODSO: Fix errors if objects exist already
  src/objects/zcl_abapgit_object_iobj.clas.abap
  src/objects/zcl_abapgit_object_odso.clas.abap
Labels: serialization, bug, ci

#5555 CHDO: Fix deletion of TADIR entries
  src/objects/zcl_abapgit_object_chdo.clas.abap
Labels: serialization, bug, ci

#5564 SSFO: Avoid side-effect in is_active
  src/objects/zcl_abapgit_object_ssfo.clas.abap
Labels: serialization

#5561 FDT0: Add check of local/transportable apps
  src/objects/zcl_abapgit_object_fdt0.clas.abap
Labels: serialization, bug, ci

#5567 Fix tag popup
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zcl_abapgit_services_git.clas.abap
Labels: user interface

#5566 CHAR: take only serialize main language into accou
  src/objects/zcl_abapgit_object_char.clas.abap
Labels: serialization

#5571 Repo view: fix "order by transport" dump
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: bug

#5560 PINF: Fix error when changing packages
  src/objects/zcl_abapgit_object_pinf.clas.abap
  src/objects/zcl_abapgit_object_pinf.clas.locals_imp.abap
Labels: serialization, bug, ci

#5514 Repo view: Show icon for different source system
  src/objects/core/zabapgit_parallel.fugr.xml
  src/objects/core/zabapgit_parallel.fugr.z_abapgit_serialize_parallel.abap
  src/objects/core/zcl_abapgit_file_status.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, user interface

#5547 SICF: Object name in upper case
  src/objects/zcl_abapgit_object_sicf.clas.abap
Labels: serialization

#5581 Fix dump for repos using data tables
  src/data/zcl_abapgit_data_serializer.clas.abap
Labels: bug

#5563 CLAS: Add to deletion transport
  src/objects/zcl_abapgit_object_clas.clas.abap
Labels: serialization, ci

#5557 Refactor: `is_active` logic
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
  src/objects/core/zcl_abapgit_objects_activation.clas.testclasses.abap
  src/objects/core/zcl_abapgit_objects_activation.clas.xml
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: refactoring

#5601 Exclude technical languages from get_installed_languages in lxe_texts
  src/objects/texts/zcl_abapgit_lxe_texts.clas.abap
Labels: translation

#5598 Exclude technical language from intf, clas, prog, dtel, doma and tabl
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_doma.clas.abap
  src/objects/zcl_abapgit_object_dtel.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
Labels: translation

#5591 Refactor: Create Tag
  src/ui/zcl_abapgit_gui_page_tag.clas.abap
  src/ui/zcl_abapgit_gui_page_tags.clas.abap
  src/ui/zcl_abapgit_gui_page_tags.clas.xml
  src/ui/zcl_abapgit_gui_router.clas.abap
Labels: user interface, refactoring
