Repository abapGit/abapGit, pull requests merged in 2022-09, with the labels that each got.

#5736 fixed "Add via Transport" short keys
  package.json
  src/ui/zcl_abapgit_gui_page_data.clas.abap
  src/ui/zcl_abapgit_gui_page_data.clas.testclasses.abap
Labels: bug

#5724 new SOBJ serializer
  src/objects/zcl_abapgit_object_sobj.clas.abap
  src/objects/zcl_abapgit_object_sobj.clas.xml
Labels: serialization

#5741 DEVC: Fix dump if package has been delete
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization, bug

#5740 Fix dump when deleting repo with DB utility
  src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo_srv.intf.abap
  src/ui/db/zcl_abapgit_gui_page_db.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: bug

#5742 Remove unused branch popup
  src/ui/zcl_abapgit_html_form_utils.clas.testclasses.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zcl_abapgit_services_basis.clas.testclasses.abap
  src/ui/zcl_abapgit_ui_injector.clas.testclasses.abap
  src/ui/zif_abapgit_popups.intf.abap
  src/zabapgit_forms.prog.abap
Labels: refactoring

#5747 G4xx, IWxx: Changed by
  src/objects/zcl_abapgit_object_g4ba.clas.abap
  src/objects/zcl_abapgit_object_g4bs.clas.abap
  src/objects/zcl_abapgit_object_iwmo.clas.abap
  src/objects/zcl_abapgit_object_iwsv.clas.abap
  src/objects/zcl_abapgit_object_iwvb.clas.abap
Labels: serialization

#5749 WDYN: Fix dump if no components exist
  src/objects/zcl_abapgit_object_wdyn.clas.abap
Labels: serialization, bug

#5745 SCVI: Sort tables to avoid diffs
  src/objects/zcl_abapgit_object_scvi.clas.abap
Labels: serialization

#5746 W3XX: Sort parameters to avoid diffs
  src/objects/zcl_abapgit_object_w3xx_super.clas.abap
Labels: serialization

#5748 SUSH,SUSC: Fix deletion
  src/objects/core/zcl_abapgit_dependencies.clas.abap
  src/objects/zcl_abapgit_object_sush.clas.abap
Labels: serialization

#5757 DSYS: Simplify namespace split
  src/objects/zcl_abapgit_object_dsys.clas.abap
Labels: serialization

#5756 DOCV: Handle namespaces
  src/objects/zcl_abapgit_object_docv.clas.abap
Labels: serialization, bug

#5750 SOTR: Fix handling of alias names
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
Labels: serialization, bug

#5753 Add uninstall option to repository overview
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#5755 CLAS,INTF: Add missing shorttexts
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
Labels: serialization

#5768 CLAS: Fix pull for deleted interface methods
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
Labels: serialization, bug
