Repository abapGit/abapGit, pull requests merged in 2022-07, with the labels that each got.

#5648 Skipping serialization for ignored objects
  package.json
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
Labels: new feature

#5670 [AFF] Get data for serialization from the DB
  abaplint.json
  ci/abaplint.json
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
Labels: aff

#5641 Repo view: Fix "View > Changes only" for offline
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5628 Improve package / sub-package check
  src/objects/core/zcl_abapgit_file_status.clas.abap
  src/objects/core/zcl_abapgit_file_status.clas.testclasses.abap
  src/objects/core/zcl_abapgit_folder_logic.clas.abap
  src/objects/core/zcl_abapgit_folder_logic.clas.testclasses.abap
Labels: serialization
