Repository abapGit/abapGit, pull requests merged in 2022-04, with the labels that each got.

#5430 Fix "dynpro_send_in_background"
  src/objects/zcl_abapgit_object_enho.clas.abap
  src/objects/zcl_abapgit_object_enhs.clas.abap
  src/objects/zcl_abapgit_object_ensc.clas.abap
  src/objects/zcl_abapgit_object_sprx.clas.abap
  src/objects/zcl_abapgit_object_tran.clas.abap
Labels: serialization

#5417 Deserialize textpool for some objects
  src/objects/zcl_abapgit_objects_program.clas.abap
Labels: serialization, ci

#5437 DDLS: Avoid dump and show error
  src/objects/zcl_abapgit_object_ddls.clas.abap
Labels: serialization

#5436 Rename methods returning boolean
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_vcls.clas.abap
  src/utils/zcl_abapgit_requirement_helper.clas.abap
Labels: refactoring

#5439 CHDO: Avoid double pull and fix uninstall
  src/objects/zcl_abapgit_object_chdo.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
Labels: serialization, bug, ci

#5438 UI: Transport popup
  src/ui/zcl_abapgit_popups.clas.abap
Labels: user interface

#5435 Record objects in transports
  src/objects/zcl_abapgit_object_area.clas.abap
  src/objects/zcl_abapgit_object_dcls.clas.abap
  src/objects/zcl_abapgit_object_ddls.clas.abap
  src/objects/zcl_abapgit_object_doct.clas.abap
  src/objects/zcl_abapgit_object_dsys.clas.abap
  src/objects/zcl_abapgit_object_srfc.clas.abap
  src/objects/zcl_abapgit_object_wdcc.clas.abap
Labels: serialization, ci

#5434 Add transport for deletions in generic serializer
  src/objects/zcl_abapgit_object_asfc.clas.abap
  src/objects/zcl_abapgit_object_g4ba.clas.abap
  src/objects/zcl_abapgit_object_g4bs.clas.abap
  src/objects/zcl_abapgit_object_iwmo.clas.abap
  src/objects/zcl_abapgit_object_iwom.clas.abap
  src/objects/zcl_abapgit_object_iwpr.clas.abap
  src/objects/zcl_abapgit_object_iwsg.clas.abap
  src/objects/zcl_abapgit_object_iwsv.clas.abap
  src/objects/zcl_abapgit_object_iwvb.clas.abap
  src/objects/zcl_abapgit_object_sppf.clas.abap
  src/objects/zcl_abapgit_object_sucu.clas.abap
  src/objects/zcl_abapgit_object_ueno.clas.abap
  src/objects/zcl_abapgit_objects_generic.clas.abap
Labels: serialization, ci

#5445 DOMA: Deletion of domains with append
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: serialization, ci

#5444 DEVC: Raise error for main/structure packages
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization, bug, ci

#5440 Improve LXE error handling
  src/objects/texts/zcl_abapgit_lxe_texts.clas.abap
Labels: translation

#5452 UI: Transport popup
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zif_abapgit_popups.intf.abap
Labels: user interface

#5456 UI: Fix escaping of textarea input
  src/ui/zcl_abapgit_html_form.clas.abap
Labels: user interface

#5450 Improve JSON syntax highlighter
  src/syntax/zcl_abapgit_syntax_factory.clas.abap
  src/syntax/zcl_abapgit_syntax_json.clas.abap
  src/syntax/zcl_abapgit_syntax_json.clas.testclasses.abap
  src/syntax/zcl_abapgit_syntax_json.clas.xml
Labels: user interface

#5461 DEVC: Fix DYNPRO_SEND_IN_BACKGROUND
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization, ci

#5459 TABU: Add "jump" to SE16
  src/data/zcl_abapgit_data_utils.clas.abap
  src/ui/zcl_abapgit_gui_router.clas.abap
Labels: user interface

#5458 Avoid logon when comparing with remote
  src/repo/zcl_abapgit_repo.clas.abap
Labels: bug

#5453 UI: Transport popup
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zif_abapgit_popups.intf.abap
Labels: user interface

#5463 Remove "Tag Overview" popup
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/zcl_abapgit_gui_router.clas.abap
  src/ui/zcl_abapgit_html_form_utils.clas.testclasses.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zcl_abapgit_services_basis.clas.testclasses.abap
  src/ui/zcl_abapgit_services_git.clas.abap
  src/ui/zcl_abapgit_tag_popups.clas.abap
  src/ui/zcl_abapgit_tag_popups.clas.xml
  src/ui/zcl_abapgit_ui_factory.clas.abap
  src/ui/zcl_abapgit_ui_injector.clas.abap
  src/ui/zcl_abapgit_ui_injector.clas.testclasses.abap
  src/ui/zif_abapgit_popups.intf.abap
  src/ui/zif_abapgit_tag_popups.intf.abap
  src/ui/zif_abapgit_tag_popups.intf.xml
  src/zif_abapgit_definitions.intf.abap
Labels: user interface, refactoring

#5487 Refactor: Database Utility
  src/ui/db/zcl_abapgit_gui_page_db.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
Labels: user interface, refactoring

#5489 FUGR: Fix diff of includes
  src/objects/zcl_abapgit_object_fugr.clas.abap
Labels: serialization, ci

#5393 Create empty classes/interfaces before DDIC
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_dtel.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_ttyp.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zif_abapgit_object.intf.abap
Labels: serialization

#5488 Allow different user/password per repository in background mode
  src/background/zcl_abapgit_background.clas.abap
Labels: bug

#5427 Properly ignore files during deserialize
  src/objects/core/zcl_abapgit_file_status.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/repo/zif_abapgit_repo.intf.abap
Labels: serialization

#5491 SPRX: Fix suppress_dialog error
  src/objects/zcl_abapgit_object_sprx.clas.abap
Labels: serialization, bug

#5493 Add "Changed by" to several objects
  src/objects/zcl_abapgit_object_ensc.clas.abap
  src/objects/zcl_abapgit_object_tran.clas.abap
  src/objects/zcl_abapgit_object_type.clas.abap
  src/objects/zcl_abapgit_object_vcls.clas.abap
  src/objects/zcl_abapgit_object_xinx.clas.abap
Labels: serialization

#5441 SOTR: Refactor
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
Labels: refactoring

#5498 Fix syntax error in BW jump
  src/objects/core/zcl_abapgit_gui_jumper.clas.abap
Labels: bug

#5505 Fix ignore count in repo statistics
  src/ui/zcl_abapgit_gui_page_sett_info.clas.abap
Labels: bug
