Repository abapGit/abapGit, pull requests merged in 2022-10, with the labels that each got.

#5773 TABL: Fix deserialize if foreign key exists
  src/objects/zcl_abapgit_object_tabl.clas.abap
Labels: serialization, bug

#5786 Prepare processing longtexts for sub components
  src/objects/texts/zcl_abapgit_longtexts.clas.abap
  src/objects/texts/zcl_abapgit_longtexts.clas.testclasses.abap
  src/objects/texts/zcl_abapgit_longtexts.clas.xml
  src/objects/texts/zif_abapgit_longtexts.intf.abap
  test/abap_transpile.json
Labels: serialization

#5797 Downport, version unit tests
  src/zcl_abapgit_version.clas.testclasses.abap
Labels: downport

#5783 Fix subcomponent text deserialization (json)
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
Labels: serialization

#5796 Various objects: Add documentation (longtexts)
  src/objects/zcl_abapgit_object_char.clas.abap
  src/objects/zcl_abapgit_object_dtel.clas.abap
  src/objects/zcl_abapgit_object_sfbf.clas.abap
  src/objects/zcl_abapgit_object_sfbs.clas.abap
  src/objects/zcl_abapgit_object_sfsw.clas.abap
  src/objects/zcl_abapgit_object_suso.clas.abap
  src/objects/zcl_abapgit_object_ttyp.clas.abap
  src/objects/zcl_abapgit_object_view.clas.abap
  src/objects/zcl_abapgit_object_wdya.clas.abap
  src/objects/zcl_abapgit_object_xinx.clas.abap
Labels: serialization

#5575 CLAS,INTF: Support for component documentation
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: serialization

#5795 FUGR: Add documentation (longtexts)
  src/objects/zcl_abapgit_object_fugr.clas.abap
Labels: serialization

#5780 W3xx: Remove unnecessary metadata
  src/objects/zcl_abapgit_object_w3xx_super.clas.abap
  src/ui/zabapgit_css_common.w3mi.xml
  src/ui/zabapgit_css_theme_belize_blue.w3mi.xml
  src/ui/zabapgit_css_theme_dark.w3mi.xml
  src/ui/zabapgit_css_theme_default.w3mi.xml
  src/ui/zabapgit_icon_font.w3mi.xml
  src/ui/zabapgit_icon_font_css.w3mi.xml
  src/ui/zabapgit_js_common.w3mi.xml
Labels: serialization

#5803 AFF: Fix existence check
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
Labels: aff

#5806 VIEW: Add translation support
  src/objects/zcl_abapgit_object_view.clas.abap
Labels: serialization, translation

#5811 ENHO: Unlock objects in cases of errors
  src/objects/enh/zcl_abapgit_object_enho_badi.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_class.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_fugr.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_hook.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_intf.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_wdyc.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_wdyn.clas.abap
Labels: serialization, bug

#5788 Improvements in html engine
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/core/zcl_abapgit_html.clas.testclasses.abap
  src/ui/core/zif_abapgit_html.intf.abap
  test/abap_transpile.json
Labels: user interface

#5789 UI repo over view page refactoring
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/zcl_abapgit_gui_component.clas.abap
  src/ui/zcl_abapgit_gui_page_main.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface, refactoring

#5810 CLAS,ENHO: Fix inactive enhancements
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: serialization, bug

#5818 DRUL: Use CL_BLUE_SOURCE_OBJECT_DATA instead of CL_DRUL_WB_OBJECT_DATA
  src/objects/zcl_abapgit_object_drul.clas.abap
Labels: serialization

#5819 UI: Add hint for "icon scaling" setting
  src/ui/zcl_abapgit_gui_page_sett_pers.clas.abap
Labels: user interface

#5828 Disable "experimental" feature for stand-alone version
  src/zcl_abapgit_settings.clas.abap
Labels: bug

#5790 UI repo over tweaks
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
  src/ui/zabapgit_js_common.w3mi.data.js
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#5841 CLAS,INTF: Catch runtime error during update
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
Labels: serialization, bug

#5840 Reset sort order to ascending in repo overview
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface
