Repository abapGit/abapGit, pull requests merged in 2022-11, with the labels that each got.

#5845 DOCV: Add object to tadir and transports
  src/objects/zcl_abapgit_object_docv.clas.abap
Labels: serialization

#5814 Local organization/grouping/labeling of repos
  src/persist/zif_abapgit_persistence.intf.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/core/zif_abapgit_html.intf.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_over.clas.locals_imp.abap
  src/ui/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/utils/zcl_abapgit_repo_labels.clas.abap
  src/utils/zcl_abapgit_repo_labels.clas.testclasses.abap
  src/utils/zcl_abapgit_repo_labels.clas.xml
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, user interface

#5851 Fix syntax highlighting for xml and html
  src/syntax/zcl_abapgit_syntax_xml.clas.abap
  src/syntax/zcl_abapgit_syntax_xml.clas.testclasses.abap
Labels: user interface

#5855 DOCV: Fix dump for namespaced documents
  src/objects/zcl_abapgit_object_docv.clas.abap
Labels: serialization, bug

#5860 Page menu provider for GUI page (and HOC)
  src/ui/zcl_abapgit_gui_page.clas.abap
  src/ui/zcl_abapgit_gui_page_hoc.clas.abap
  src/ui/zif_abapgit_gui_menu_provider.intf.abap
  src/ui/zif_abapgit_gui_menu_provider.intf.xml
Labels: user interface, refactoring

#5861 Repo overview: Add labels and links to command palette
  src/ui/zabapgit_js_common.w3mi.data.js
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#5863 Add "Show Hotkeys" to Help Menu
  src/ui/core/zif_abapgit_gui_hotkey_ctl.intf.abap
  src/ui/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/zcl_abapgit_gui_hotkey_ctl.clas.abap
  src/ui/zcl_abapgit_gui_router.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: user interface

#5862 AFF object RONT
  src/objects/aff/zcl_abapgit_object_ront.clas.abap
  src/objects/aff/zcl_abapgit_object_ront.clas.xml
Labels: aff

#5866 AFF object NONT
  src/objects/aff/zcl_abapgit_object_nont.clas.abap
  src/objects/aff/zcl_abapgit_object_nont.clas.xml
Labels: aff

#5864 Repo view: Render labels
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5865 Command palette refactoring
  src/ui/zabapgit_js_common.w3mi.data.js
  src/ui/zcl_abapgit_gui_chunk_lib.clas.abap
Labels: refactoring

#5859 Repo overview page, Polishing
  src/ui/zabapgit_css_theme_dark.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
  src/ui/zabapgit_js_common.w3mi.data.js
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/zcl_abapgit_gui_page_stage.clas.abap
  src/utils/zcl_abapgit_repo_labels.clas.abap
  src/utils/zcl_abapgit_repo_labels.clas.testclasses.abap
  src/zcl_abapgit_settings.clas.abap
Labels: user interface

#5873 TOBJ: Deletion of logical transport objects
  src/objects/zcl_abapgit_object_tobj.clas.abap
Labels: serialization

#5881 Add a couple icons
  src/ui/zabapgit_icon_font.w3mi.data.woff
  src/ui/zabapgit_icon_font_css.w3mi.data.css
Labels: user interface

#5880 Fix type for data config serialize
  src/data/zcl_abapgit_data_config.clas.abap
Labels: serialization

#5882 Add "Sponsor us" to page footer
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
  src/ui/zcl_abapgit_gui_page.clas.abap
Labels: user interface

#5885 Open "Sponsor us" in new browser window
  src/ui/zcl_abapgit_gui_page.clas.abap
  src/ui/zcl_abapgit_gui_router.clas.abap
  src/ui/zcl_abapgit_services_abapgit.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: user interface

#5888 New Online/Offline: Add labels form input
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo_srv.intf.abap
  src/ui/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/zcl_abapgit_services_repo.clas.abap
  src/ui/zif_abapgit_services_repo.intf.abap
Labels: new feature

#5893 Fix command palette form submit
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: bug

#5890 Repo View: Fix cross-out for menu items
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5889 Repo View: Consolidate "Stage" and "Force Stage"
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5894 Enable Command Palette for radio buttons
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: user interface

#5896 page repo: add patch function
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5899 page code inspector: add actions to command palette
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: user interface

#5891 add label F4 value help
  src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo_srv.intf.abap
  src/ui/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/zcl_abapgit_html_form_utils.clas.testclasses.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zcl_abapgit_services_basis.clas.testclasses.abap
  src/ui/zcl_abapgit_ui_injector.clas.testclasses.abap
  src/ui/zif_abapgit_popups.intf.abap
Labels: new feature
