Repository abapGit/abapGit, pull requests merged in 2022-02, with the labels that each got.

#5310 WAPA: Fix repeated pull of BSP page (Fiori)
  src/objects/zcl_abapgit_object_wapa.clas.abap
Labels: serialization

#5304 DOMA: Fix serialize of translations
  src/objects/zcl_abapgit_object_doma.clas.abap
Labels: serialization

#5302 Refactor: Activation log
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/utils/zcl_abapgit_log.clas.abap
Labels: refactoring

#5303 TABL: Properly show inactive objects
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: serialization

#5315 UI: Center Popups - Part 3
  src/objects/zcl_abapgit_objects.clas.abap
  src/utils/zcl_abapgit_requirement_helper.clas.abap
  src/xml/zcl_abapgit_xml.clas.abap
Labels: user interface

#5313 Detect JSON files during pull
  src/objects/core/zcl_abapgit_file_status.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.testclasses.abap
  src/objects/zcl_abapgit_objects.clas.abap
Labels: bug

#5311 Improve progress bar and log for pull
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
Labels: user interface

#5350 DTEL: REF TO DATA for DDIC element support
  src/objects/zcl_abapgit_object_dtel.clas.abap
Labels: serialization

#5381 SOTS: Fix dump in case of lower case language code
  src/objects/zcl_abapgit_object_sots.clas.abap
Labels: serialization, bug

#5384 TYPE: Fix pull/activate table type ref to data type
  src/objects/zcl_abapgit_object_ttyp.clas.abap
Labels: serialization, bug

#5374 CLAS/INTF: Fix serialize/deserialize of documentation
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: serialization, bug
