Repository abapGit/abapGit, pull requests merged in 2022-12, with the labels that each got.

#5902 Fix file to object mapping
  src/objects/core/zcl_abapgit_filename_logic.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.testclasses.abap
Labels: bug, ci

#5901 Fix JS init error on Diff/Patch page
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: bug

#5906 Repo Settings: Fix dump in 702
  src/ui/zcl_abapgit_gui_page_sett_info.clas.abap
Labels: bug, downport

#5897 Remove static references to `cl_oo_source`
  src/apack/zcl_abapgit_apack_migration.clas.abap
  src/objects/oo/zcl_abapgit_oo_serializer.clas.abap
Labels: refactoring

#5907 Remove aliases - HTML class
  src/ui/core/zcl_abapgit_html.clas.abap
Labels: refactoring

#5911 All/none label filter
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#5913 Fix detection of SAP GUI for Windows
  src/ui/zcl_abapgit_frontend_services.clas.abap
Labels: bug

#5914 Diff/Patch: Improve beacons
  src/utils/zcl_abapgit_diff.clas.abap
  src/utils/zcl_abapgit_diff.clas.testclasses.abap
  test/abap_transpile.json
Labels: bug

#5915 Copy (yank) link texts with y+LinkHints
  src/ui/zabapgit_js_common.w3mi.data.js
  src/ui/zcl_abapgit_gui_hotkey_ctl.clas.abap
  src/ui/zcl_abapgit_gui_router.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, user interface

#5918 Diff/Patch: Improve beacons
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
Labels: user interface

#5916 Set transport request in local repo settings or user exit
  src/cts/zcl_abapgit_transport.clas.abap
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/persist/zif_abapgit_persistence.intf.abap
  src/ui/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/zcl_abapgit_services_repo.clas.abap
  src/ui/zif_abapgit_popups.intf.abap
  src/zcl_abapgit_exit.clas.abap
  src/zif_abapgit_exit.intf.abap
Labels: new feature

#5925 Repo View: Fallback to main if branch doesn't exist
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/repo/zif_abapgit_repo_online.intf.abap
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: bug

#5927 Improve repository URL validation
  src/git_platform/zcl_abapgit_git_url.clas.abap
  src/ui/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/zcl_abapgit_gui_page_sett_remo.clas.abap
Labels: user interface

#5933 Diff/Patch: Improve beacons follow-up
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
Labels: bug

#5929 Update to Hotkeys
  src/ui/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/zcl_abapgit_gui_hotkey_ctl.clas.abap
  src/ui/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface

#5931 UI: Fix dark theme buttons for Chrome
  src/ui/zabapgit_css_theme_dark.w3mi.data.css
Labels: user interface

#5934 AFF: Add NONT and RONT to registry
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
Labels: aff

#5940 DB Util: Fix error saving non-XML data
  src/persist/zcl_abapgit_persistence_db.clas.abap
Labels: bug

#5943 ENHO: Fix error deserializing enhancements
  src/objects/core/zcl_abapgit_file_deserialize.clas.abap
Labels: serialization, bug

#5946 Reorg: Package hierarchy
  src/exits/package.devc.xml
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zcl_abapgit_exit.clas.xml
  src/exits/zif_abapgit_exit.intf.abap
  src/exits/zif_abapgit_exit.intf.xml
  src/http/zcl_abapgit_login_manager.clas.abap
  src/http/zcl_abapgit_login_manager.clas.testclasses.abap
  src/http/zcl_abapgit_login_manager.clas.xml
  src/http/zcl_abapgit_url.clas.abap
  src/http/zcl_abapgit_url.clas.testclasses.abap
  src/http/zcl_abapgit_url.clas.xml
  src/inspect/package.devc.xml
  src/inspect/zcl_abapgit_code_inspector.clas.abap
  src/inspect/zcl_abapgit_code_inspector.clas.xml
  src/inspect/zif_abapgit_code_inspector.intf.abap
  src/inspect/zif_abapgit_code_inspector.intf.xml
  src/objects/jump/package.devc.xml
  src/objects/jump/zcl_abapgit_adt_link.clas.abap
  src/objects/jump/zcl_abapgit_adt_link.clas.xml
  src/objects/jump/zcl_abapgit_gui_jumper.clas.abap
  src/objects/jump/zcl_abapgit_gui_jumper.clas.xml
  src/objects/jump/zif_abapgit_gui_jumper.intf.abap
  src/objects/jump/zif_abapgit_gui_jumper.intf.xml
  src/objects/rules/package.devc.xml
  src/objects/rules/zcl_abapgit_field_rules.clas.abap
  src/objects/rules/zcl_abapgit_field_rules.clas.xml
  src/objects/rules/zif_abapgit_field_rules.intf.abap
  src/objects/rules/zif_abapgit_field_rules.intf.xml
  src/stage/package.devc.xml
  src/stage/zcl_abapgit_merge.clas.abap
  src/stage/zcl_abapgit_merge.clas.xml
  src/stage/zcl_abapgit_stage.clas.abap
  src/stage/zcl_abapgit_stage.clas.xml
  src/stage/zcl_abapgit_stage_logic.clas.abap
  src/stage/zcl_abapgit_stage_logic.clas.xml
  src/stage/zif_abapgit_merge.intf.abap
  src/stage/zif_abapgit_merge.intf.xml
  src/stage/zif_abapgit_stage_logic.intf.abap
  src/stage/zif_abapgit_stage_logic.intf.xml
  src/utils/zcl_abapgit_news.clas.abap
  src/utils/zcl_abapgit_news.clas.testclasses.abap
  src/utils/zcl_abapgit_news.clas.xml
  src/utils/zcl_abapgit_version.clas.abap
  src/utils/zcl_abapgit_version.clas.testclasses.abap
  src/utils/zcl_abapgit_version.clas.xml
  test/abap_transpile.json
Labels: refactoring

#5947 Add status message after pulls
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: user interface

#5948 Add "ignore sub-packages" option for offline repos
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo_srv.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_addofflin.clas.abap
Labels: user interface

#5950 DRUL: Use CL_BLUE_SOURCE_OBJECT_DATA2 instead of CL_BLUE_SOURCE_OBJECT_DATA
  src/objects/zcl_abapgit_object_drul.clas.abap
Labels: bug

#5951 Repo View: Consolidate "Pull" and "Selective Pull"
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/routing/zcl_abapgit_services_git.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: user interface, refactoring

#5952 Prevent pull in case of duplicate files
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/objects/core/zcl_abapgit_objects_check.clas.testclasses.abap
Labels: bug
