Repository abapGit/abapGit, pull requests merged in 2022-06, with the labels that each got.

#5608 DSYS: Fix exceptions
  src/objects/zcl_abapgit_object_dsys.clas.abap
Labels: serialization

#5609 AFF: Fix exception handling
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
Labels: serialization

#5558 SOTR: Fix uninstall
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
Labels: serialization, bug

#5613 Fix dump when switching repo to offline
  src/ui/zcl_abapgit_gui_page_sett_remo.clas.abap
Labels: bug

#5619 Remove aliases - Common AFF
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
Labels: serialization

#5618 W3xx: Replace call with `TADIR_INSERT`
  src/objects/zcl_abapgit_object_w3xx_super.clas.abap
Labels: serialization

#5616 UI: Message box improvements
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zcl_abapgit_gui_chunk_lib.clas.abap
Labels: user interface

#5622 FUGR: Better maintenance view auto comments cleanups
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.testclasses.abap
  src/objects/zcl_abapgit_objects_program.clas.xml
  src/zcx_abapgit_exception.clas.abap
Labels: serialization

#5635 Clear IWOM/IWMO object metadata
  src/objects/zcl_abapgit_object_iwmo.clas.abap
  src/objects/zcl_abapgit_object_iwom.clas.abap
Labels: serialization

#5637 Clear IWPR and IWSV metadata fields
  src/objects/zcl_abapgit_object_iwpr.clas.abap
  src/objects/zcl_abapgit_object_iwsv.clas.abap
Labels: serialization

#5647 Clear IWVB metadata fields
  src/objects/zcl_abapgit_object_iwvb.clas.abap
Labels: serialization

#5640 Remove aliases - Repo services
  src/repo/zcl_abapgit_repo_srv.clas.abap
Labels: refactoring

#5649 Fix repo settings dialog
  src/ui/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/ui/zcl_abapgit_html_form.clas.abap
Labels: user interface

#5664 Downport: GUI HTML Viewer
  src/ui/zcl_abapgit_html_viewer_gui.clas.abap
Labels: bug, downport

#5662 Improve folder logic popup
  src/ui/zcl_abapgit_popups.clas.abap
Labels: user interface

#5667 Rename repo interface method implementations
  src/repo/zcl_abapgit_repo.clas.abap
Labels: refactoring
