Repository abapGit/abapGit, pull requests merged in 2023-03, with the labels that each got.

#6093 Better pull dialog, Screen status
  package.json
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
  src/persist/zcl_abapgit_persist_migrate.clas.abap
  src/persist/zcl_abapgit_persist_migrate.clas.locals_imp.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/ui/zcl_abapgit_popups.clas.locals_imp.abap
  src/ui/zif_abapgit_popups.intf.abap
  src/zabapgit.prog.xml
  src/zif_abapgit_definitions.intf.abap
Labels: user interface

#6121 Fix ITAB_DUPLICATE_KEY dump during deserialize
  src/objects/core/zcl_abapgit_file_status.clas.abap
Labels: bug

#6127 CLAS: Fix variable name
  src/objects/zcl_abapgit_object_clas.clas.abap
Labels: refactoring

#6139 Fix check for unsaved data in local settings
  src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_locl.clas.abap
Labels: bug, user interface

#6141 DEVC: Fix error handling
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization

#6137 Pull dialog: Usability
  src/persist/zcl_abapgit_persist_migrate.clas.abap
  src/zabapgit.prog.xml
Labels: user interface

#6134 Refactoring of DB pages, and new UI features
  src/persist/zcl_abapgit_persistence_db.clas.abap
  src/ui/core/zcl_abapgit_gui.clas.abap
  src/ui/core/zcl_abapgit_gui_asset_manager.clas.abap
  src/ui/core/zcl_abapgit_gui_asset_manager.clas.testclasses.abap
  src/ui/core/zcl_abapgit_gui_html_processor.clas.testclasses.abap
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/core/zcl_abapgit_html.clas.testclasses.abap
  src/ui/core/zif_abapgit_gui_asset_manager.intf.abap
  src/ui/core/zif_abapgit_gui_services.intf.abap
  src/ui/core/zif_abapgit_html.intf.abap
  src/ui/lib/zcl_abapgit_html_table.clas.abap
  src/ui/lib/zcl_abapgit_html_table.clas.testclasses.abap
  src/ui/lib/zcl_abapgit_html_table.clas.xml
  src/ui/lib/zcl_abapgit_html_toolbar.clas.abap
  src/ui/lib/zif_abapgit_gui_page_title.intf.abap
  src/ui/lib/zif_abapgit_gui_page_title.intf.xml
  src/ui/lib/zif_abapgit_html_table.intf.abap
  src/ui/lib/zif_abapgit_html_table.intf.xml
  src/ui/pages/zabapgit_css_page_db.w3mi.data.css
  src/ui/pages/zabapgit_css_page_db.w3mi.xml
  src/ui/pages/zabapgit_css_page_db_entry.w3mi.data.css
  src/ui/pages/zabapgit_css_page_db_entry.w3mi.xml
  src/ui/pages/zcl_abapgit_gui_page.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db_dis.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db_edit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db_entry.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db_entry.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_hoc.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
  src/ui/zcl_abapgit_ui_factory.clas.abap
  src/ui/zcl_abapgit_ui_injector.clas.locals_imp.abap
  src/utils/zcl_abapgit_string_buffer.clas.abap
  src/utils/zcl_abapgit_string_buffer.clas.xml
Labels: user interface

#6150 Rename "Repository Overview" to "Repository List"
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.xml
Labels: refactoring

#6146 Fix namespace check for AFF
  src/repo/zcl_abapgit_file_status.clas.locals_imp.abap
  src/repo/zcl_abapgit_file_status.clas.testclasses.abap
Labels: serialization, bug, aff

#6147 Fix unit test in serializer class
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
Labels: serialization

#6157 data: throw error if hitting max
  src/data/zcl_abapgit_data_serializer.clas.abap
  src/data/zcl_abapgit_data_serializer.clas.testclasses.abap
Labels: serialization

#6167 Fix detection of inactive objects
  src/repo/zcl_abapgit_file_status.clas.abap
  src/repo/zcl_abapgit_file_status.clas.testclasses.abap
Labels: serialization, bug

#6145 SICF: Add missing error pages
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
  src/objects/texts/zcl_abapgit_sots_handler.clas.abap
  src/objects/texts/zcl_abapgit_sots_handler.clas.xml
  src/objects/zcl_abapgit_object_sicf.clas.abap
  src/objects/zcl_abapgit_object_sots.clas.abap
Labels: serialization, bug

#6171 Update CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: documentation

#6173 new user exit: change allowed object types
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zif_abapgit_exit.intf.abap
  src/objects/zcl_abapgit_objects.clas.abap
Labels: new feature, exit

#6168 USE_LXE settings and serialization of selected languages (in old format)
  src/objects/core/zabapgit_parallel.fugr.xml
  src/objects/core/zabapgit_parallel.fugr.z_abapgit_serialize_parallel.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/texts/zcl_abapgit_lxe_texts.clas.abap
  src/objects/texts/zcl_abapgit_lxe_texts.clas.testclasses.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_doma.clas.abap
  src/objects/zcl_abapgit_object_dtel.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_msag.clas.abap
  src/objects/zcl_abapgit_object_para.clas.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/objects/zcl_abapgit_object_shi3.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_tran.clas.abap
  src/objects/zcl_abapgit_object_view.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
  src/repo/zcl_abapgit_dot_abapgit.clas.abap
  src/repo/zif_abapgit_dot_abapgit.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/zif_abapgit_definitions.intf.abap
  test/abap_transpile.json
Labels: translation
