Repository abapGit/abapGit, pull requests merged in 2023-06, with the labels that each got.

#6306 IDOC, TABL: Set released and closed status
  src/objects/zcl_abapgit_object_idoc.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
Labels: serialization

#6309 Fix is_dirty check for Repo Settings
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: bug, user interface

#6299 Consolidate READ/INSERT/DELETE REPORT statements
  abaplint.json
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
  src/objects/oo/zcl_abapgit_oo_serializer.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/sap/zcl_abapgit_sap_report.clas.abap
  src/objects/sap/zcl_abapgit_sap_report.clas.xml
  src/objects/sap/zif_abapgit_sap_report.intf.abap
  src/objects/sap/zif_abapgit_sap_report.intf.xml
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/objects/zcl_abapgit_object_type.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
  src/zcl_abapgit_factory.clas.abap
  src/zcl_abapgit_injector.clas.abap
Labels: serialization, refactoring

#6325 bugfix, dump GETWA_NOT_ASSIGNED
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
Labels: bug

#6328 Fix syntax error in `zcl_abapgit_file_deserialize`
  src/objects/core/zcl_abapgit_file_deserialize.clas.abap
Labels: bug, downport
