Repository abapGit/abapGit, pull requests merged in 2023-04, with the labels that each got.

#6184 AQSG, AQQU: Add jump to object
  src/objects/zcl_abapgit_object_aqqu.clas.abap
  src/objects/zcl_abapgit_object_aqsg.clas.abap
Labels: serialization

#6170 REUSE License Compliance
  .github/workflows/reuse.yml
  .reuse/dep5
  LICENSES/CC-BY-4.0.txt
  LICENSES/MIT.txt
  README.md
Labels: documentation

#6196 Refactor Unit Test Page
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
Labels: user interface, refactoring

#6191 TABU: Several enhancements
  src/cts/zcl_abapgit_cts_api.clas.abap
  src/cts/zif_abapgit_cts_api.intf.abap
  src/data/zcl_abapgit_data_config.clas.abap
  src/data/zcl_abapgit_data_deserializer.clas.abap
  src/data/zcl_abapgit_data_serializer.clas.abap
  src/data/zcl_abapgit_data_utils.clas.abap
  src/data/zcl_abapgit_data_utils.clas.testclasses.abap
  src/data/zif_abapgit_data_deserializer.intf.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/persist/zif_abapgit_persistence.intf.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_data.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature

#6198 CLAS: Refactor skip of SADL classes
  src/objects/core/zcl_abapgit_skip_objects.clas.abap
  src/objects/core/zcl_abapgit_skip_objects.clas.xml
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
Labels: serialization, refactoring

#6211 Fix checksums on pull with new objects
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_checksums.clas.locals_imp.abap
Labels: serialization, repo

#6212 Check repo package against namespace
  src/repo/zcl_abapgit_file_status.clas.locals_imp.abap
Labels: serialization

#6217 One more SHI3 language deserialization fix
  src/objects/zcl_abapgit_object_shi3.clas.abap
Labels: serialization

#6213 Improve "Advanced > Unit Tests"
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
Labels: repo

#6218 Improve copy&paste on diff page
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: bug, user interface

#6219 Avoid remote connection for uninstalling repo
  src/repo/zcl_abapgit_repo.clas.abap
Labels: repo

#6223 run unit page: fix back button
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
Labels: bug, user interface

#6226 Add some icons
  src/ui/zabapgit_icon_font.w3mi.data.woff
  src/ui/zabapgit_icon_font_css.w3mi.data.css
Labels: user interface

#6239 Add debug option to show href-links on hover
  src/ui/core/zcl_abapgit_html.clas.abap
Labels: new feature

#6237 Fix xstring conversion on non-Unicode systems
  src/utils/zcl_abapgit_convert.clas.abap
Labels: bug

#6228 Improve deletion of OTR texts
  package.json
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
Labels: serialization

#6232 Refactor adding entries to transport
  src/cts/zcl_abapgit_cts_api.clas.abap
  src/cts/zif_abapgit_cts_api.intf.abap
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
  src/objects/zcl_abapgit_object_cmpt.clas.abap
  src/objects/zcl_abapgit_object_cus0.clas.abap
  src/objects/zcl_abapgit_object_cus1.clas.abap
  src/objects/zcl_abapgit_object_msag.clas.abap
  src/objects/zcl_abapgit_object_para.clas.abap
  src/objects/zcl_abapgit_object_saxx_super.clas.abap
  src/objects/zcl_abapgit_object_udmo.clas.abap
  src/objects/zcl_abapgit_object_vcls.clas.abap
  src/objects/zcl_abapgit_object_xinx.clas.abap
  src/objects/zcl_abapgit_objects_generic.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: refactoring

#6240 ECATT: Avoid diffs between dialog and background
  src/objects/zcl_abapgit_object_ecatt_super.clas.abap
Labels: serialization
