Repository abapGit/abapGit, pull requests merged in 2023-12, with the labels that each got.

#6682 CLAS: Fix deserializing child exception classes
  src/objects/zcl_abapgit_object_clas.clas.abap
Labels: serialization, bug

#6685 IOBJ: Fix uninstall
  src/objects/zcl_abapgit_object_iobj.clas.abap
Labels: serialization, bug

#6683 TABU: Fix staging in background process
  src/stage/zcl_abapgit_stage_logic.clas.abap
Labels: serialization, bug

#6684 TABU: Fix deserializing data config
  src/objects/core/zcl_abapgit_filename_logic.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.testclasses.abap
Labels: serialization, bug

#6681 Check for ABAP language version during serialize
  src/objects/zcl_abapgit_objects_super.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.testclasses.abap
Labels: serialization

#6690 refactor `zcl_abapgit_services_abapgit`
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
  src/ui/routing/zcl_abapgit_services_abapgit.clas.abap
  src/zabapgit_forms.prog.abap
Labels: refactoring

#6693 Fix ABAP language version check
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.testclasses.abap
  src/utils/zcl_abapgit_zip.clas.abap
Labels: bug

#6698 Reorg packages (1)
  src/objects/sap/zcl_abapgit_function_module.clas.abap
  src/objects/sap/zcl_abapgit_function_module.clas.xml
  src/objects/sap/zif_abapgit_function_module.intf.abap
  src/objects/sap/zif_abapgit_function_module.intf.xml
  src/persist/zcl_abapgit_migrations.clas.abap
  src/persist/zcl_abapgit_migrations.clas.xml
  src/ui/progress/package.devc.xml
  src/ui/progress/zcl_abapgit_progress.clas.abap
  src/ui/progress/zcl_abapgit_progress.clas.xml
  src/ui/progress/zif_abapgit_progress.intf.abap
  src/ui/progress/zif_abapgit_progress.intf.xml
Labels: refactoring

#6694 TABL refactoring, serializing XML
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.locals_imp.abap
  src/objects/zif_abapgit_object_tabl.intf.abap
  src/objects/zif_abapgit_object_tabl.intf.xml
Labels: serialization, refactoring

#6699 Reorg packages (2)
  src/env/package.devc.xml
  src/env/zcl_abapgit_abap_language_vers.clas.abap
  src/env/zcl_abapgit_abap_language_vers.clas.testclasses.abap
  src/env/zcl_abapgit_abap_language_vers.clas.xml
  src/env/zcl_abapgit_environment.clas.abap
  src/env/zcl_abapgit_environment.clas.testclasses.abap
  src/env/zcl_abapgit_environment.clas.xml
  src/env/zcl_abapgit_feature.clas.abap
  src/env/zcl_abapgit_feature.clas.testclasses.abap
  src/env/zcl_abapgit_feature.clas.xml
  src/env/zcl_abapgit_language.clas.abap
  src/env/zcl_abapgit_language.clas.xml
  src/env/zcl_abapgit_settings.clas.abap
  src/env/zcl_abapgit_settings.clas.xml
  src/env/zcl_abapgit_user_record.clas.abap
  src/env/zcl_abapgit_user_record.clas.testclasses.abap
  src/env/zcl_abapgit_user_record.clas.xml
  src/env/zif_abapgit_environment.intf.abap
  src/env/zif_abapgit_environment.intf.xml
  test/abap_transpile.json
Labels: refactoring

#6709 CLAS: Avoid popups in lower releases
  src/objects/zcl_abapgit_object_clas.clas.abap
Labels: serialization

#6708 Debug info: Show exits coded in exit super class
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
Labels: user interface, exit

#6711 FUGR: Fix check if include belong to function grp
  src/objects/zcl_abapgit_object_fugr.clas.abap
Labels: serialization

#6713 Protect `tadir` selection
  src/objects/core/zcl_abapgit_tadir.clas.abap
Labels: refactoring

#6716 Fix abapGit popups external call
  src/ui/zcl_abapgit_popups.clas.locals_imp.abap
Labels: user interface

#6717 Reorg packages (4)
  src/repo/filter/package.devc.xml
  src/repo/filter/zcl_abapgit_object_filter_tran.clas.abap
  src/repo/filter/zcl_abapgit_object_filter_tran.clas.testclasses.abap
  src/repo/filter/zcl_abapgit_object_filter_tran.clas.xml
  src/repo/filter/zcl_abapgit_repo_filter.clas.abap
  src/repo/filter/zcl_abapgit_repo_filter.clas.xml
  src/repo/filter/zif_abapgit_object_filter.intf.abap
  src/repo/filter/zif_abapgit_object_filter.intf.xml
Labels: refactoring

#6715 New feature: Original system
  abaplint.json
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_dot_abapgit.clas.abap
  src/repo/zcl_abapgit_repo_status.clas.abap
  src/repo/zif_abapgit_dot_abapgit.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: serialization, new feature, user interface

#6719 Repo status: Replace input with repo interface
  src/repo/stage/zcl_abapgit_stage_logic.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/repo/zcl_abapgit_repo_status.clas.abap
  src/repo/zif_abapgit_repo.intf.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.testclasses.abap
Labels: refactoring, repo
