Repository abapGit/abapGit, pull requests merged in 2023-08, with the labels that each got.

#6375 Do the ABAP Language Version for the AFF objects
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.testclasses.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.xml
Labels: aff

#6391 Clarify minimum version
  README.md
Labels: documentation

#6393 Enhance experimental features
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_aff_registry.clas.testclasses.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.testclasses.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_pdts.clas.testclasses.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_glob.clas.abap
  src/zcl_abapgit_settings.clas.abap
  src/zcl_abapgit_settings.clas.testclasses.abap
  src/zcl_abapgit_settings.clas.xml
Labels: new feature, refactoring

#6398 Fix unit test in `zcl_abapgit_objects`
  src/objects/zcl_abapgit_objects.clas.testclasses.abap
Labels: refactoring

#6394 TABU: Fix deserializing data
  src/objects/core/zcl_abapgit_objects_check.clas.abap
Labels: serialization, bug

#6400 SKTD - Knowledge Transfer Document
  src/objects/zcl_abapgit_object_sktd.clas.abap
  src/objects/zcl_abapgit_object_sktd.clas.xml
Labels: serialization

#6396 Refactor Data Config Page
  src/ui/pages/zcl_abapgit_gui_page_data.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: refactoring

#6397 Fix unit test page if there are no unit tests
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
Labels: user interface

#6402 DRUL: fix changed_by()
  src/objects/zcl_abapgit_object_drul.clas.abap
Labels: serialization

#6403 APIS - API Release State
  src/objects/zcl_abapgit_object_apis.clas.abap
  src/objects/zcl_abapgit_object_apis.clas.xml
Labels: serialization

#6404 SOD1/2: Check for support and add changed_by
  src/objects/zcl_abapgit_object_sod1.clas.abap
  src/objects/zcl_abapgit_object_sod2.clas.abap
Labels: serialization

#6410 Move `check_and_create_package` to repo services
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/routing/zcl_abapgit_services_basis.clas.abap
  src/ui/routing/zcl_abapgit_services_basis.clas.xml
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.testclasses.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.xml
Labels: refactoring, repo

#6399 generic object handler: fix unit test
  src/objects/zcl_abapgit_objects_generic.clas.abap
Labels: serialization

#6413 Rename `zcl_abapgit_file_status`
  src/objects/core/zcl_abapgit_file_deserialize.clas.abap
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_status.clas.abap
  src/repo/zcl_abapgit_repo_status.clas.locals_imp.abap
  src/repo/zcl_abapgit_repo_status.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_status.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_sett_info.clas.abap
  test/abap_transpile.json
Labels: refactoring, repo

#6432 Improve confusing progress message (seemingly always 200 objects)
  src/git/zcl_abapgit_git_pack.clas.abap
  src/git/zcl_abapgit_git_pack.clas.testclasses.abap
Labels: user interface

#6431 DSYS: Fix error for objects containing `/` in name
  src/objects/zcl_abapgit_object_dsys.clas.abap
Labels: serialization, bug

#6439 DSYS: Update spacing between methods
  src/objects/zcl_abapgit_object_dsys.clas.abap
Labels: serialization, refactoring

#6437 Downport: Fix syntax errors in unit tests
  src/git/zcl_abapgit_git_commit.clas.testclasses.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.testclasses.abap
Labels: downport

#6438 APACK: Remove unnecessary statement
  src/apack/zcl_abapgit_apack_reader.clas.abap
Labels: refactoring

#6444 generic object handler: fix special cases
  src/objects/zcl_abapgit_objects_generic.clas.abap
Labels: serialization, bug

#6440 Remove `status` from `zcl_abapgit_repo`
  src/cts/zcl_abapgit_transport_2_branch.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/stage/zcl_abapgit_stage_logic.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: refactoring, repo

#6447 Clarify error messages about folder logic
  src/objects/core/zcl_abapgit_folder_logic.clas.abap
Labels: user interface

#6448 Fix typo in repo settings
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: user interface
