Repository abapGit/abapGit, pull requests merged in 2023-01, with the labels that each got.

#5968 Fix "duplicate file error" during pull
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/objects/core/zcl_abapgit_objects_check.clas.testclasses.abap
Labels: bug

#5972 Fix menus with many items
  src/ui/zabapgit_css_common.w3mi.data.css
Labels: user interface

#5971 Fix syntax highlight for XML, CSS, JS
  src/syntax/zcl_abapgit_syntax_css.clas.abap
  src/syntax/zcl_abapgit_syntax_js.clas.abap
  src/syntax/zcl_abapgit_syntax_xml.clas.abap
  src/syntax/zcl_abapgit_syntax_xml.clas.testclasses.abap
Labels: bug, user interface

#5949 Refactor: Remove `delete_tadir` flag
  src/objects/zcl_abapgit_object_amsd.clas.abap
  src/objects/zcl_abapgit_object_asfc.clas.abap
  src/objects/zcl_abapgit_object_auth.clas.abap
  src/objects/zcl_abapgit_object_avar.clas.abap
  src/objects/zcl_abapgit_object_bdef.clas.abap
  src/objects/zcl_abapgit_object_cmpt.clas.abap
  src/objects/zcl_abapgit_object_cus0.clas.abap
  src/objects/zcl_abapgit_object_cus1.clas.abap
  src/objects/zcl_abapgit_object_dcls.clas.abap
  src/objects/zcl_abapgit_object_ddls.clas.abap
  src/objects/zcl_abapgit_object_ddlx.clas.abap
  src/objects/zcl_abapgit_object_docv.clas.abap
  src/objects/zcl_abapgit_object_drul.clas.abap
  src/objects/zcl_abapgit_object_dsys.clas.abap
  src/objects/zcl_abapgit_object_dtdc.clas.abap
  src/objects/zcl_abapgit_object_fdt0.clas.abap
  src/objects/zcl_abapgit_object_form.clas.abap
  src/objects/zcl_abapgit_object_ftgl.clas.abap
  src/objects/zcl_abapgit_object_g4ba.clas.abap
  src/objects/zcl_abapgit_object_g4bs.clas.abap
  src/objects/zcl_abapgit_object_iobj.clas.abap
  src/objects/zcl_abapgit_object_iwmo.clas.abap
  src/objects/zcl_abapgit_object_iwom.clas.abap
  src/objects/zcl_abapgit_object_iwpr.clas.abap
  src/objects/zcl_abapgit_object_iwsg.clas.abap
  src/objects/zcl_abapgit_object_iwsv.clas.abap
  src/objects/zcl_abapgit_object_iwvb.clas.abap
  src/objects/zcl_abapgit_object_jobd.clas.abap
  src/objects/zcl_abapgit_object_oa2p.clas.abap
  src/objects/zcl_abapgit_object_pers.clas.abap
  src/objects/zcl_abapgit_object_prag.clas.abap
  src/objects/zcl_abapgit_object_saxx_super.clas.abap
  src/objects/zcl_abapgit_object_sfbf.clas.abap
  src/objects/zcl_abapgit_object_sfbs.clas.abap
  src/objects/zcl_abapgit_object_smtg.clas.abap
  src/objects/zcl_abapgit_object_sobj.clas.abap
  src/objects/zcl_abapgit_object_splo.clas.abap
  src/objects/zcl_abapgit_object_sppf.clas.abap
  src/objects/zcl_abapgit_object_sqsc.clas.abap
  src/objects/zcl_abapgit_object_srfc.clas.abap
  src/objects/zcl_abapgit_object_srvb.clas.abap
  src/objects/zcl_abapgit_object_srvd.clas.abap
  src/objects/zcl_abapgit_object_ssfo.clas.abap
  src/objects/zcl_abapgit_object_ssst.clas.abap
  src/objects/zcl_abapgit_object_styl.clas.abap
  src/objects/zcl_abapgit_object_sucu.clas.abap
  src/objects/zcl_abapgit_object_susc.clas.abap
  src/objects/zcl_abapgit_object_sush.clas.abap
  src/objects/zcl_abapgit_object_tobj.clas.abap
  src/objects/zcl_abapgit_object_ucsa.clas.abap
  src/objects/zcl_abapgit_object_vcls.clas.abap
  src/objects/zcl_abapgit_object_w3xx_super.clas.abap
  src/objects/zcl_abapgit_object_wdcc.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zcl_abapgit_objects_bridge.clas.abap
  src/objects/zcl_abapgit_objects_generic.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: refactoring, ci

#5976 Page diff/patch: Follow-up for small files
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
Labels: user interface

#5975 SMIM: Record deletion of objects in transport
  src/objects/zcl_abapgit_object_smim.clas.abap
Labels: serialization

#5974 Pull log: Show deletion of unnecessary objects
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: serialization

#5980 Refactor: CSS clean-up
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_dark.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
Labels: refactoring

#5984 Fix Diff: Ignore comment edge cases
  src/utils/zcl_abapgit_diff.clas.abap
  src/utils/zcl_abapgit_diff.clas.testclasses.abap
  test/abap_transpile.json
Labels: bug

#5979 Allow Object Types with multiple files in AFF
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
Labels: aff

#5981 CLAS,INTF: Removing STATE field in XML
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
Labels: serialization

#5986 Update AFF to new AJSON functionality
  src/objects/aff/zcl_abapgit_json_handler.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
Labels: aff

#5988 Debug Info: Display of Deserialization Step
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
Labels: user interface

#5982 Pull log: Include object counts
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
Labels: user interface

#5991 DRUL: Fix compatibility with lower releases
  src/objects/zcl_abapgit_object_drul.clas.abap
Labels: serialization

#5996 Uninstall log: Show only if there are errors
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: user interface

#5997 Fix CI test runs triggered from unit tests
  src/test/zcl_abapgit_objects_ci_tests.clas.abap
Labels: bug

#5985 Repo View: Selectively add objects on pull
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: user interface

#5994 Repo View: Activate objects
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature

#5995 XSLT: Avoid double activation
  src/objects/zcl_abapgit_object_xslt.clas.abap
Labels: serialization

#5998 DOMA: Fix domains with custom conversion exit
  src/objects/zcl_abapgit_object_doma.clas.abap
Labels: serialization, bug

#5999 SHLP: Avoid double activation
  src/objects/zcl_abapgit_object_shlp.clas.abap
Labels: serialization

#6001 SAPC: Fix uninstall errors
  src/objects/core/zcl_abapgit_dependencies.clas.abap
Labels: serialization, bug

#6000 PDTS: Fix recording in transport
  src/objects/zcl_abapgit_object_pdts.clas.abap
Labels: serialization, ci

#6007 TOBJ: Improve error messages
  src/objects/zcl_abapgit_object_tobj.clas.abap
Labels: serialization

#5989 TABL,VIEW: Simplify deserialize
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_view.clas.abap
Labels: serialization, bug

#6008 Refactor: `MESSAGE ... INTO`
  src/cts/zcl_abapgit_transport.clas.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/zcl_abapgit_object_auth.clas.abap
  src/objects/zcl_abapgit_object_oa2p.clas.abap
  src/objects/zcl_abapgit_object_scvi.clas.abap
  src/objects/zcl_abapgit_object_stvi.clas.abap
  src/objects/zcl_abapgit_object_suso.clas.abap
  src/objects/zcl_abapgit_object_xinx.clas.abap
  src/zcx_abapgit_exception.clas.abap
  src/zcx_abapgit_exception.clas.testclasses.abap
Labels: refactoring

#6009 Enhancement for Object Selector
  src/ui/zcl_abapgit_popups.clas.abap
Labels: new feature
