Repository abapGit/abapGit, pull requests merged in 2023-05, with the labels that each got.

#6246 Fix unhandled exception in SRVB
  src/objects/zcl_abapgit_object_srvb.clas.abap
Labels: serialization, bug

#6235 Enhance Serializer Interface - Filename Logic
  src/objects/core/zcl_abapgit_filename_logic.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.testclasses.abap
  src/objects/zcl_abapgit_object_devc.clas.abap
  src/objects/zcl_abapgit_objects_bridge.clas.abap
  src/objects/zif_abapgit_object.intf.abap
  test/abap_transpile.json
Labels: serialization, refactoring

#6251 DEVC: Clear TPCLASS
  deps/scompkdtln.tabl.xml
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization

#6250 FUGR,CLAS: Enhance "jump to"
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zif_abapgit_object.intf.abap
  src/ui/lib/zcl_abapgit_html_action_utils.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: serialization, new feature

#6249 New UserExit at REPO TOOLBAR for adding custom repo settings
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zif_abapgit_exit.intf.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
Labels: new feature, exit

#6255 clear NROB fields
  src/objects/zcl_abapgit_object_nrob.clas.abap
Labels: serialization

#6259 INTF, WEBI: Hide objects generated by proxy (SPRX)
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_webi.clas.abap
Labels: serialization

#6268 Fix dump related to exit implementations
  src/exits/zcl_abapgit_exit.clas.abap
Labels: bug, exit

#6261 Add GUI and HTML control info to page footer
  src/ui/pages/zcl_abapgit_gui_page.clas.abap
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: user interface

#6271 Ensure unique form ids
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/lib/zcl_abapgit_html_form.clas.abap
Labels: user interface

#6274 FUGR, CLAS: Enhance "changed by"
  src/background/zcl_abapgit_background_push_au.clas.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: serialization, new feature

#6275 SICF: Remove special TADIR logic
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/objects/zcl_abapgit_object_sicf.clas.abap
Labels: serialization, refactoring

#6284 Remove unused class
  src/ui/zcl_abapgit_free_sel_dialog.clas.abap
  src/ui/zcl_abapgit_free_sel_dialog.clas.xml
Labels: refactoring

#6283 Add fallback for ADT transport link
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface

#6285 Reorg packages
  src/exits/zcl_abapgit_auth.clas.abap
  src/exits/zcl_abapgit_auth.clas.testclasses.abap
  src/exits/zcl_abapgit_auth.clas.xml
  src/exits/zif_abapgit_auth.intf.abap
  src/exits/zif_abapgit_auth.intf.xml
  src/objects/sap/package.devc.xml
  src/objects/sap/zcl_abapgit_sap_namespace.clas.abap
  src/objects/sap/zcl_abapgit_sap_namespace.clas.xml
  src/objects/sap/zcl_abapgit_sap_package.clas.abap
  src/objects/sap/zcl_abapgit_sap_package.clas.xml
  src/objects/sap/zif_abapgit_sap_namespace.intf.abap
  src/objects/sap/zif_abapgit_sap_namespace.intf.xml
  src/objects/sap/zif_abapgit_sap_package.intf.abap
  src/objects/sap/zif_abapgit_sap_package.intf.xml
  src/utils/zcl_abapgit_environment.clas.abap
  src/utils/zcl_abapgit_environment.clas.testclasses.abap
  src/utils/zcl_abapgit_environment.clas.xml
  src/utils/zcl_abapgit_zip.clas.abap
  src/utils/zcl_abapgit_zip.clas.xml
  test/abap_transpile.json
Labels: refactoring

#6297 Repo view: Show icon for different original language
  src/objects/core/zabapgit_parallel.fugr.z_abapgit_serialize_parallel.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/repo/zcl_abapgit_file_status.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, user interface

#6303 Pull dialog safeguard
  src/ui/zcl_abapgit_popups.clas.locals_imp.abap
Labels: bug
