Repository abapGit/abapGit, pull requests merged in 2023-11, with the labels that each got.

#6606 Replace `TR_TADIR_INTERFACE` with `tadir_delete`
  src/objects/zcl_abapgit_object_enhc.clas.abap
  src/objects/zcl_abapgit_object_shma.clas.abap
  src/objects/zcl_abapgit_object_susc.clas.abap
Labels: serialization, refactoring

#6603 Add ABAP Language Version to New Online/Offline
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo_srv.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/ui/routing/zif_abapgit_services_repo.intf.abap
Labels: user interface

#6605 Refactor "Go Back"
  src/ui/pages/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_codi_base.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_commit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_data.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db_entry.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_ex_object.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_ex_pckage.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_sel.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tags.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface, refactoring

#6582 FUGR: Fix import of template screens
  src/objects/zcl_abapgit_objects_program.clas.abap
Labels: serialization

#6611 Show object type in activation log
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
Labels: user interface

#6610 Fix "Open in Main Language" if language is not installed
  src/objects/jump/zcl_abapgit_gui_jumper.clas.abap
Labels: user interface

#6616 Clean-up `select_add_order_by`
  src/objects/zcl_abapgit_object_doma.clas.abap
  src/objects/zcl_abapgit_object_dtel.clas.abap
  src/objects/zcl_abapgit_object_fdt0.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
  src/objects/zcl_abapgit_object_iwmo.clas.abap
  src/objects/zcl_abapgit_object_iwsv.clas.abap
  src/objects/zcl_abapgit_object_iwvb.clas.abap
  src/objects/zcl_abapgit_object_msag.clas.abap
  src/objects/zcl_abapgit_object_nspc.clas.abap
  src/objects/zcl_abapgit_object_sicf.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_tran.clas.abap
  src/objects/zcl_abapgit_object_ueno.clas.abap
  src/objects/zcl_abapgit_object_view.clas.abap
Labels: refactoring

#6614 APACK: Manifest interface in sub-package
  src/apack/zcl_abapgit_apack_reader.clas.abap
Labels: bug

#6615 Clean-up `select_single_full_key`
  abaplint.json
  src/objects/zcl_abapgit_object_doct.clas.abap
  src/objects/zcl_abapgit_object_docv.clas.abap
  src/objects/zcl_abapgit_object_dsys.clas.abap
  src/objects/zcl_abapgit_object_sots.clas.abap
  src/objects/zcl_abapgit_object_suso.clas.abap
  src/objects/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_type.clas.abap
  src/persist/zcl_abapgit_persist_migrate.clas.abap
Labels: refactoring

#6609 SSFO: Fix order of T_CAPTION data
  src/objects/zcl_abapgit_object_ssfo.clas.abap
Labels: serialization

#6617 Improve Backup
  src/ui/pages/zcl_abapgit_gui_page_db.clas.abap
Labels: user interface

#6621 Fix dump restoring abapGit backup
  src/ui/pages/zcl_abapgit_gui_page_db.clas.abap
Labels: bug

#6622 Fix typo in "orange" label
  src/ui/pages/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
Labels: user interface

#6623 Sort pull request popup
  src/ui/popups/zcl_abapgit_popup_pull_request.clas.abap
Labels: user interface

#6566 SAP GUI for HTML: Fix dialog buttons
  src/ui/lib/zcl_abapgit_html_form.clas.abap
  src/ui/lib/zcl_abapgit_html_form_utils.clas.testclasses.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_dark.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
Labels: bug, user interface

#6613 Change order of popups on pull
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: user interface

#6612 APACK: Allow overwriting missing dependencies
  src/apack/zcl_abapgit_apack_helper.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: user interface

#6630 Add icons for issue, pr, action
  src/ui/zabapgit_icon_font.w3mi.data.woff
  src/ui/zabapgit_icon_font_css.w3mi.data.css
Labels: user interface

#6628 INTF: Fix file format feature switch
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: serialization

#6632 Fix text field when switching to offline
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
Labels: user interface

#6633 Add "name" to repository settings (prep)
  src/persist/zif_abapgit_persist_repo.intf.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: user interface, refactoring

#6636 Clean-up `select_add_order_by`
  abaplint.json
  src/apack/zcl_abapgit_apack_helper.clas.abap
  src/apack/zcl_abapgit_apack_reader.clas.abap
  src/data/zcl_abapgit_data_deserializer.clas.abap
  src/data/zcl_abapgit_data_serializer.clas.abap
  src/data/zcl_abapgit_data_supporter.clas.abap
  src/inspect/zcl_abapgit_code_inspector.clas.abap
  src/objects/texts/zcl_abapgit_longtexts.clas.abap
  src/objects/texts/zcl_abapgit_sotr_handler.clas.abap
  src/repo/zcl_abapgit_object_filter_tran.clas.abap
  src/ui/routing/zcl_abapgit_services_abapgit.clas.abap
Labels: refactoring

#6637 Add "name" to repository settings (3)
  src/ui/pages/zcl_abapgit_gui_page_db.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: new feature, user interface

#6638 Consolidate offline and online repo view
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/repo/zcl_abapgit_repo_offline.clas.abap
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/repo/zif_abapgit_repo.intf.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.testclasses.abap
Labels: repo

#6640 Fix deletion/uninstall when using local settings
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo.intf.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.testclasses.abap
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: bug, repo

#6642 Enhance repo labels
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/utils/zcl_abapgit_repo_labels.clas.abap
Labels: new feature, user interface

#6646 ZCL_ABAPGIT_SERIALIZE / DETERMINE_MAX_PROCESSES refactoring
  src/exits/zcl_abapgit_exit.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.testclasses.abap
  src/utils/zcl_abapgit_environment.clas.abap
  src/zcl_abapgit_injector.clas.abap
  src/zif_abapgit_environment.intf.abap
Labels: refactoring

#6647 Rename private method in `zcl_abapgit_objects`
  src/objects/zcl_abapgit_objects.clas.abap
Labels: refactoring

#6651 Repo List: Make labels clickable
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#6656 packages: remove `scompkdtln` from public scope
  src/objects/core/zcl_abapgit_folder_logic.clas.abap
  src/objects/sap/zcl_abapgit_sap_package.clas.abap
  src/objects/sap/zif_abapgit_sap_package.intf.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zif_abapgit_popups.intf.abap
Labels: refactoring

#6664 Fix filename for export to ZIP
  src/utils/zcl_abapgit_zip.clas.abap
Labels: bug

#6666 Support short/long timestamps in field rules
  src/objects/rules/zcl_abapgit_field_rules.clas.abap
  src/objects/rules/zcl_abapgit_field_rules.clas.testclasses.abap
  src/objects/rules/zcl_abapgit_field_rules.clas.xml
Labels: serialization

#6663 Add "Ignore" option for ABAP Language Version
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
  src/repo/zif_abapgit_dot_abapgit.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
Labels: repo

#6669 Downport: Fix 702 syntax errors
  src/objects/zcl_abapgit_object_ssfo.clas.abap
  src/objects/zcl_abapgit_object_ueno.clas.abap
Labels: downport

#6674 Fix lines between methods
  src/exits/zcl_abapgit_exit.clas.abap
  src/git/zcl_abapgit_git_time.clas.abap
  src/http/zcl_abapgit_http_client.clas.abap
  src/objects/core/zcl_abapgit_function_module.clas.abap
Labels: refactoring

#6673 put `zcl_abapgit_default_transport` behind interface
  src/cts/zcl_abapgit_default_transport.clas.abap
  src/cts/zif_abapgit_default_transport.intf.abap
  src/cts/zif_abapgit_default_transport.intf.xml
  src/objects/zcl_abapgit_object_sod1.clas.abap
  src/objects/zcl_abapgit_object_sod2.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/zcl_abapgit_factory.clas.abap
Labels: refactoring

#6678 Remove unused variable
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: refactoring

#6677 Remember last used folder
  src/cts/zcl_abapgit_transport_mass.clas.locals_imp.abap
  src/ui/zcl_abapgit_frontend_services.clas.abap
  src/ui/zcl_abapgit_frontend_services.clas.testclasses.abap
  src/ui/zcl_abapgit_frontend_services.clas.xml
  src/utils/zcl_abapgit_zip.clas.abap
Labels: user interface

#6680 Add "Ignore" to tests for ABAP language version
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.testclasses.abap
Labels: serialization
