Repository abapGit/abapGit, pull requests merged in 2023-02, with the labels that each got.

#6020 SFBF, SFBS, SFSW: Major bug fixes
  src/objects/zcl_abapgit_object_sfbf.clas.abap
  src/objects/zcl_abapgit_object_sfbs.clas.abap
  src/objects/zcl_abapgit_object_sfsw.clas.abap
Labels: serialization, bug, ci

#6022 Enhance login popup
  src/ui/routing/zcl_abapgit_services_abapgit.clas.abap
  src/zabapgit_password_dialog.prog.abap
Labels: refactoring, documentation

#6030 Add icon for experimental features
  src/ui/zabapgit_icon_font.w3mi.data.woff
  src/ui/zabapgit_icon_font_css.w3mi.data.css
Labels: user interface

#6047 CLAS: Fix recording of changes in transport
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: serialization, bug

#6050 Visualize when experimental features are enabled
  src/ui/lib/zcl_abapgit_gui_buttons.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_main.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_main.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface

#6054 Fix hotkeys in repo view
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: bug, user interface

#6053 Refactor: Order exit methods
  src/exits/zif_abapgit_exit.intf.abap
Labels: refactoring

#6055 TABL: Fix activation of secondary indexes
  src/objects/zcl_abapgit_object_tabl.clas.abap
Labels: serialization, bug

#6057 Refactor: replace newline/crlf with built-in
  src/background/zcl_abapgit_background_push_au.clas.abap
  src/background/zcl_abapgit_background_push_fi.clas.abap
  src/objects/core/zcl_abapgit_objects_files.clas.abap
  src/objects/core/zcl_abapgit_objects_files.clas.testclasses.abap
  src/objects/zcl_abapgit_object_wapa.clas.abap
  src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_commit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_db_dis.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_res.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_glob.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_info.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tags.clas.abap
  src/ui/routing/zcl_abapgit_services_git.clas.abap
  src/utils/zcl_abapgit_diff.clas.abap
  src/utils/zcl_abapgit_diff.clas.testclasses.abap
  src/zif_abapgit_definitions.intf.abap
Labels: refactoring

#6058 Escape output for plain text highlighter
  src/syntax/zcl_abapgit_syntax_txt.clas.abap
Labels: user interface

#6059 Fix highlighting in case of back quotes
  src/syntax/zcl_abapgit_syntax_css.clas.abap
  src/syntax/zcl_abapgit_syntax_js.clas.abap
  src/syntax/zcl_abapgit_syntax_xml.clas.abap
  src/syntax/zcl_abapgit_syntax_xml.clas.testclasses.abap
Labels: user interface

#6062 Fix hotkeys repo list
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#6064 Prevent dump if too many requests are selected
  src/ui/zcl_abapgit_popups.clas.abap
Labels: bug

#6085 LXE: move ty_lxe_i18n to private section
  src/objects/texts/zcl_abapgit_lxe_texts.clas.abap
  src/objects/texts/zif_abapgit_lxe_texts.intf.abap
Labels: refactoring

#6092 JavaScript clean-up: Remove obsolete parts
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: refactoring

#6089 Refactor popup_to_select_from_list
  src/apack/zcl_abapgit_apack_helper.clas.abap
  src/ui/lib/zcl_abapgit_exception_viewer.clas.abap
  src/ui/lib/zcl_abapgit_log_viewer.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/ui/zcl_abapgit_free_sel_dialog.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zcl_abapgit_popups.clas.locals_imp.abap
  src/ui/zif_abapgit_popups.intf.abap
  src/utils/zcl_abapgit_requirement_helper.clas.abap
  src/zabapgit_password_dialog.prog.abap
Labels: user interface, refactoring

#6094 JavaScript update comments
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: documentation

#6096 Add icon for tags
  src/ui/zabapgit_icon_font.w3mi.data.woff
  src/ui/zabapgit_icon_font_css.w3mi.data.css
Labels: user interface

#6095 Fix tag deletion
  src/git/zcl_abapgit_git_branch_list.clas.abap
  src/git/zcl_abapgit_git_porcelain.clas.abap
  src/git/zcl_abapgit_git_tag.clas.abap
  src/git/zcl_abapgit_git_transport.clas.abap
  src/ui/routing/zcl_abapgit_services_git.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: bug

#6052 JavaScript lint/format
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: refactoring

#6098 Improve visualization of tags
  src/git/zcl_abapgit_git_branch_list.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/routing/zcl_abapgit_services_git.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
Labels: user interface

#6102 CLAS: Fix error when changing redefinitions
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
Labels: serialization, bug

#6101 Refactor: Empty packfile logic
  src/git/zcl_abapgit_git_porcelain.clas.abap
Labels: refactoring
