Repository abapGit/abapGit, pull requests merged in 2023-07, with the labels that each got.

#6326 Fix dialog exit
  src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_bckg.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_glob.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tags.clas.abap
Labels: user interface

#6305 replace `seoclskey` with `abap_classname`
  src/exits/zif_abapgit_exit.intf.abap
Labels: refactoring

#6336 Fix GUI actions for Edge browser control
  src/ui/core/zcl_abapgit_gui_event.clas.abap
Labels: user interface

#6343 Fix Code Inspector jump
  src/ui/pages/zcl_abapgit_gui_page_codi_base.clas.abap
Labels: bug, user interface

#6348 Enable object handler for Event Consumption Model (EEEC)
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/aff/zcl_abapgit_object_eeec.clas.abap
  src/objects/aff/zcl_abapgit_object_eeec.clas.xml
Labels: serialization

#6344 Fix hotkeys for edge browser control
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: bug

#6359 SOD1/SOD2 downport 702 + fix endless loop
  src/objects/zcl_abapgit_object_sod1.clas.abap
  src/objects/zcl_abapgit_object_sod2.clas.abap
Labels: serialization, bug, downport

#6360 Enhance jump to object
  src/objects/zcl_abapgit_objects.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface

#6346 Introduce ABAP Language Version base functionality
  abaplint.json
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_dot_abapgit.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zif_abapgit_dot_abapgit.intf.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.xml
  src/zif_abapgit_definitions.intf.abap
Labels: new feature

#6320 Handling unsupported objects in deserialize process
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/objects/zif_abapgit_objects.intf.abap
Labels: serialization, user interface

#6369 move more git definitions
  src/git/zcl_abapgit_git_branch_list.clas.abap
  src/git/zcl_abapgit_git_branch_list.clas.testclasses.abap
  src/git/zcl_abapgit_git_porcelain.clas.abap
  src/git/zcl_abapgit_git_tag.clas.abap
  src/git/zif_abapgit_git_definitions.intf.abap
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/lib/zcl_abapgit_html_popups.clas.locals_imp.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_sel.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tags.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: refactoring

#6368 refactor ZCL_ABAPGIT_HTML_POPUPS
  src/ui/lib/zcl_abapgit_html_popups.clas.abap
  src/ui/lib/zcl_abapgit_html_popups.clas.locals_imp.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/popups/zcl_abapgit_popup_branch_list.clas.abap
  src/ui/popups/zcl_abapgit_popup_branch_list.clas.xml
  src/ui/popups/zcl_abapgit_popup_pull_request.clas.abap
  src/ui/popups/zcl_abapgit_popup_pull_request.clas.xml
  src/ui/popups/zcl_abapgit_popup_tag_list.clas.abap
  src/ui/popups/zcl_abapgit_popup_tag_list.clas.xml
Labels: refactoring
