Repository abapGit/abapGit, pull requests merged in 2023-09, with the labels that each got.

#6451 Replace `zcl_abapgit_objects=>ty_serialization` with same type in interface
  src/objects/core/zabapgit_parallel.fugr.z_abapgit_serialize_parallel.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zcl_abapgit_objects.clas.testclasses.abap
  src/utils/zcl_abapgit_zip.clas.abap
Labels: refactoring

#6455 Remove unused constant for ABAP Language Version
  src/zif_abapgit_definitions.intf.abap
Labels: refactoring

#6462 Apply filter after TADIR selection
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/objects/core/zif_abapgit_tadir.intf.abap
  test/zcl_abapgit_tadir_test.clas.abap
  test/zcl_abapgit_tadir_test.clas.testclasses.abap
  test/zcl_abapgit_tadir_test.clas.xml
Labels: performance

#6395 Fix update of checksums on pull
  src/objects/core/zcl_abapgit_objects_files.clas.abap
Labels: serialization, repo

#6457 CLAS/INTF: Fix `seocompotx` during deserialization
  ci/abaplint.json
  deps/seoc.type.abap
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
Labels: serialization, bug

#6469 CLAS/INTF: Fix type
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
Labels: bug

#6468 Fix dump in `ZCL_ABAPGIT_GIT_PACK=>DECODE`
  src/git/zcl_abapgit_git_pack.clas.abap
Labels: bug

#6464 Consolidate `READ/UPDATE_PROGDIR` calls
  src/objects/sap/zcl_abapgit_sap_report.clas.abap
  src/objects/sap/zif_abapgit_sap_report.intf.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
Labels: refactoring

#6470 Move `check_for_restart` from `zcl_abapgit_repo`
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: refactoring

#6475 Downport: Unit tests for `zcl_abapgit_objects`
  src/objects/zcl_abapgit_objects.clas.testclasses.abap
Labels: downport

#6478 Repo view: Fix display of original system
  src/objects/core/zcl_abapgit_serialize.clas.abap
Labels: serialization, bug

#6480 Consider filter at `zcl_abapgit_repo_status=>calculate`
  src/repo/zcl_abapgit_repo_status.clas.abap
  src/stage/zcl_abapgit_stage_logic.clas.abap
Labels: performance

#6485 Update auth-check in `zcl_abapgit_sap_report`
  src/objects/sap/zcl_abapgit_sap_report.clas.abap
Labels: refactoring

#6486 Add ABAP Language Version to parallel serialize
  deps/uccheck.dtel.xml
  src/objects/core/zabapgit_parallel.fugr.xml
  src/objects/core/zabapgit_parallel.fugr.z_abapgit_serialize_parallel.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
Labels: serialization

#6493 Remove test data container variants on pull that do not exist on the remote
  src/objects/ecatt/zcl_abapgit_ecatt_data_upload.clas.abap
  src/objects/zcl_abapgit_object_ecatt_super.clas.abap
Labels: serialization

#6494 ECTD: Fix diff after import based on sort order
  src/objects/zcl_abapgit_object_ecatt_super.clas.abap
Labels: serialization, bug

#6500 Fix dump in when using namespaced package for repo
  src/objects/sap/zif_abapgit_sap_namespace.intf.abap
Labels: bug

#6498 Move up ON_EVENT exit call
  src/ui/core/zcl_abapgit_gui.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: exit

#6499 Add option to remove all objects but keep repository
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo_srv.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature

#6488 Add ABAP Language Version to Repo Settings (experimental)
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: user interface

#6508 Fix command palette default form action with edge
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: user interface

#6509 Fix link hints for radio buttons with edge control
  src/ui/lib/zcl_abapgit_html_form.clas.abap
Labels: user interface

#6511 Diff View: Collapse/expand all diffs
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
Labels: new feature

#6484 Enhance ABAP Language Version class
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.testclasses.abap
  src/utils/zcl_abapgit_abap_language_vers.clas.xml
  test/abap_transpile.json
Labels: serialization

#6517 Refactor: Simplify lock check for workbench objects
  src/objects/zcl_abapgit_object_devc.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_para.clas.abap
  src/objects/zcl_abapgit_object_pinf.clas.abap
  src/objects/zcl_abapgit_object_tran.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: serialization, refactoring

#6518 W3xx: Refactor `get_metadata`
  src/objects/zcl_abapgit_object_w3xx_super.clas.abap
Labels: serialization, refactoring

#6519 SFxx: Fix missing lock checks and unlocking
  src/objects/zcl_abapgit_object_sfbf.clas.abap
  src/objects/zcl_abapgit_object_sfbs.clas.abap
  src/objects/zcl_abapgit_object_sfsw.clas.abap
Labels: serialization, bug

#6515 IAMU v2: Serialize MIMEs as separate file + fixes
  src/objects/core/zcl_abapgit_file_deserialize.clas.abap
  src/objects/zcl_abapgit_object_iamu.clas.abap
  src/utils/zcl_abapgit_convert.clas.abap
  src/utils/zcl_abapgit_convert.clas.testclasses.abap
Labels: serialization, bug

#6520 refactor user record class
  src/utils/zcl_abapgit_user_record.clas.abap
Labels: refactoring
