Repository abapGit/abapGit, pull requests merged in 2023-10, with the labels that each got.

#6524 Diff: Fix refresh of single file
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
Labels: bug, user interface

#6527 CUS2: Add missing tadir and transport entries
  src/objects/zcl_abapgit_object_cus2.clas.abap
Labels: serialization, bug

#6529 Refactor: Naming of class constants
  abaplint.json
  src/background/zcl_abapgit_background.clas.abap
  src/objects/aff/zcl_abapgit_object_evtb.clas.abap
  src/objects/aff/zcl_abapgit_object_nont.clas.abap
  src/objects/aff/zcl_abapgit_object_ront.clas.abap
  src/objects/ecatt/zcl_abapgit_ecatt_helper.clas.abap
  src/objects/zcl_abapgit_object_apis.clas.abap
  src/objects/zcl_abapgit_object_ecatt_super.clas.abap
  src/objects/zcl_abapgit_object_srvd.clas.abap
  src/objects/zcl_abapgit_object_ssfo.clas.abap
  src/objects/zcl_abapgit_object_susc.clas.abap
  src/ui/core/zcl_abapgit_gui.clas.abap
  src/ui/core/zcl_abapgit_html_viewer_gui.clas.abap
  src/ui/core/zif_abapgit_html_viewer.intf.abap
  src/utils/zcl_abapgit_diff.clas.abap
  src/utils/zcl_abapgit_diff.clas.testclasses.abap
Labels: refactoring

#6526 CMPT: Fix missing transport entry on deletion
  src/objects/zcl_abapgit_object_cmpt.clas.abap
Labels: serialization, bug

#6476 Handle ABAP Language Version for source code objects
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/sap/zcl_abapgit_sap_report.clas.abap
  src/objects/sap/zif_abapgit_sap_report.intf.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_devc.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/objects/zcl_abapgit_object_type.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: new feature

#6533 unit test page: add re-run button
  package.json
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
Labels: user interface

#6539 Change global exit class to singleton
  src/exits/zcl_abapgit_exit.clas.abap
Labels: refactoring, exit

#6538 Fix ignoring sub-packages when adding offline repo
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
Labels: bug, user interface

#6541 Refactor: Update HTML form exit method
  src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
  src/ui/lib/zcl_abapgit_html_form_utils.clas.testclasses.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_bckg.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_glob.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: user interface, refactoring

#6543 Improve unit test page
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
  src/utils/zcl_abapgit_timer.clas.testclasses.abap
Labels: user interface

#6542 Refactor: Fix observations
  package.json
  src/objects/sap/zcl_abapgit_sap_report.clas.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_devc.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/objects/zcl_abapgit_objects_super.clas.abap
Labels: refactoring

#6550 SRVB: Clear metadata links
  src/objects/zcl_abapgit_object_srvb.clas.abap
Labels: serialization

#6553 Refac: use constants
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
Labels: refactoring

#6503 Add exit to adjust rfc server group for parallel serialization
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zif_abapgit_exit.intf.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
Labels: new feature, exit

#6554 Implement `changed_by` for several objects
  src/objects/zcl_abapgit_object_asfc.clas.abap
  src/objects/zcl_abapgit_object_cus0.clas.abap
  src/objects/zcl_abapgit_object_cus1.clas.abap
  src/objects/zcl_abapgit_object_cus2.clas.abap
  src/objects/zcl_abapgit_object_dial.clas.abap
  src/objects/zcl_abapgit_object_ftgl.clas.abap
  src/objects/zcl_abapgit_object_iamu.clas.abap
  src/objects/zcl_abapgit_object_iarp.clas.abap
  src/objects/zcl_abapgit_object_iatu.clas.abap
  src/objects/zcl_abapgit_object_iaxu.clas.abap
  src/objects/zcl_abapgit_object_jobd.clas.abap
  src/objects/zcl_abapgit_object_pers.clas.abap
  src/objects/zcl_abapgit_object_prag.clas.abap
  src/objects/zcl_abapgit_object_shi5.clas.abap
  src/objects/zcl_abapgit_object_shi8.clas.abap
  src/objects/zcl_abapgit_object_sppf.clas.abap
  src/objects/zcl_abapgit_object_sqsc.clas.abap
  src/objects/zcl_abapgit_object_sucu.clas.abap
  src/objects/zcl_abapgit_object_susc.clas.abap
  src/objects/zcl_abapgit_object_suso.clas.abap
  src/objects/zcl_abapgit_object_ucsa.clas.abap
Labels: serialization

#6559 fix 'determine_max_processes' for disabled Parallel Processing
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
Labels: bug

#6555 Repo View: Shorten URL display
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
Labels: user interface

#6562 Downport: Fix syntax error related to table `ftgl_id`
  src/objects/zcl_abapgit_object_ftgl.clas.abap
Labels: downport

#6560 ZCL_ABAPGIT_SERIALIZE: Refactor Unit Tests
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
Labels: refactoring

#6563 Fix "lines between methods"
  src/objects/aff/zcl_abapgit_object_eeec.clas.abap
  src/objects/ecatt/zcl_abapgit_ecatt_config_downl.clas.abap
  src/objects/ecatt/zcl_abapgit_ecatt_data_downl.clas.abap
  src/objects/ecatt/zcl_abapgit_ecatt_data_upload.clas.abap
  src/objects/ecatt/zcl_abapgit_ecatt_sp_download.clas.abap
  src/objects/ecatt/zcl_abapgit_ecatt_system_upl.clas.abap
  src/objects/sap/zcl_abapgit_sap_namespace.clas.abap
  src/objects/zcl_abapgit_object_pdxx_super.clas.abap
  src/objects/zcl_abapgit_objects_factory.clas.abap
  src/objects/zcl_abapgit_objects_injector.clas.abap
  src/persist/zcl_abapgit_persist_factory.clas.abap
  src/persist/zcl_abapgit_persist_injector.clas.abap
  src/repo/zcl_abapgit_object_filter_tran.clas.abap
  src/ui/core/zcl_abapgit_gui_event.clas.abap
  src/ui/popups/zcl_abapgit_popup_branch_list.clas.abap
  src/ui/popups/zcl_abapgit_popup_pull_request.clas.abap
  src/ui/popups/zcl_abapgit_popup_tag_list.clas.abap
Labels: downport

#6565 Clean-up `unnecessary_pragma`
  abaplint.json
  src/objects/core/zcl_abapgit_objects_check.clas.testclasses.abap
  src/zcx_abapgit_exception.clas.testclasses.abap
Labels: refactoring

#6556 Pass repo metadata to `adjust_display_filename` exit
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zif_abapgit_exit.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: exit

#6557 PROG, FUGR: Fix handling of inactive code
  deps/r3state.dtel.xml
  src/objects/sap/zcl_abapgit_sap_report.clas.abap
  src/objects/zcl_abapgit_objects_program.clas.abap
Labels: serialization, bug

#6564 Clean-up `unused_variables`
  abaplint.json
  src/data/zcl_abapgit_data_deserializer.clas.abap
  src/data/zcl_abapgit_data_deserializer.clas.testclasses.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/objects/sap/zcl_abapgit_sap_namespace.clas.abap
  src/objects/texts/zcl_abapgit_lxe_texts.clas.abap
  src/objects/texts/zcl_abapgit_po_file.clas.testclasses.abap
  src/objects/texts/zcl_abapgit_sots_handler.clas.abap
  src/objects/zcl_abapgit_object_aifc.clas.abap
  src/objects/zcl_abapgit_object_para.clas.abap
  src/objects/zcl_abapgit_object_sktd.clas.abap
  src/objects/zcl_abapgit_object_view.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/persist/zcl_abapgit_persist_migrate.clas.locals_imp.abap
  src/repo/zcl_abapgit_repo_status.clas.locals_imp.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_info.clas.abap
  src/utils/zcl_abapgit_string_map.clas.abap
  src/xml/zcl_abapgit_xml.clas.testclasses.abap
  src/xml/zcl_abapgit_xml_input.clas.abap
  src/xml/zcl_abapgit_xml_output.clas.abap
  test/zcl_abapgit_tadir_test.clas.testclasses.abap
Labels: refactoring

#6572 Pretty-print a couple files
  src/exits/zif_abapgit_exit.intf.abap
  src/ui/pages/zcl_abapgit_gui_page_db.clas.abap
Labels: refactoring

#6573 Clean-up `double_spaces`
  src/objects/oo/zcl_abapgit_oo_serializer.clas.testclasses.abap
  src/objects/sap/zcl_abapgit_sap_namespace.clas.testclasses.abap
  src/ui/core/zcl_abapgit_gui_hotkey_ctl.clas.abap
  src/ui/lib/zcl_abapgit_exception_viewer.clas.abap
  src/ui/lib/zcl_abapgit_gui_page.clas.abap
  src/ui/lib/zcl_abapgit_html_toolbar.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_commit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tags.clas.abap
  src/ui/zcl_abapgit_popups.clas.locals_imp.abap
Labels: refactoring

#6575 Clean-up `double_spaces` (2)
  src/data/zcl_abapgit_data_deserializer.clas.abap
  src/data/zcl_abapgit_data_supporter.clas.abap
  src/objects/aff/zcl_abapgit_json_handler.clas.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/core/zcl_abapgit_tadir.clas.abap
  src/objects/texts/zcl_abapgit_longtexts.clas.abap
  src/objects/texts/zcl_abapgit_po_file.clas.abap
  src/objects/texts/zcl_abapgit_sots_handler.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
  src/objects/zcl_abapgit_object_pdts.clas.testclasses.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_object_filter_tran.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/routing/zcl_abapgit_services_git.clas.abap
  src/utils/zcl_abapgit_utils.clas.testclasses.abap
  test/zcl_abapgit_tadir_test.clas.testclasses.abap
Labels: refactoring

#6577 Clean-up `slow_parameter_passing`
  abaplint.json
  src/background/zif_abapgit_background.intf.abap
  src/objects/zcl_abapgit_object_pinf.clas.locals_def.abap
  src/objects/zcl_abapgit_object_ueno.clas.abap
  src/objects/zcl_abapgit_objects.clas.testclasses.abap
  src/repo/zcl_abapgit_dot_abapgit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge.clas.abap
  src/zcx_abapgit_exception.clas.abap
Labels: refactoring

#6581 Refactor: GUI buttons and menus
  src/ui/lib/zcl_abapgit_gui_buttons.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/lib/zcl_abapgit_gui_menus.clas.abap
  src/ui/lib/zcl_abapgit_gui_menus.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_run_bckg.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_bckg.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_glob.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_info.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tutorial.clas.abap
Labels: user interface, refactoring

#6583 Add comments explaining "icon scaling"
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/lib/zcl_abapgit_gui_page.clas.abap
Labels: documentation

#6578 TABL: Drop secondary indexes on pull
  src/objects/zcl_abapgit_object_tabl.clas.abap
Labels: serialization

#6588 Extract calls to FM FUNCTION_EXISTS
  src/objects/core/zcl_abapgit_function_module.clas.abap
  src/objects/core/zcl_abapgit_function_module.clas.xml
  src/objects/core/zcl_abapgit_objects_activation.clas.abap
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/core/zif_abapgit_function_module.intf.abap
  src/objects/core/zif_abapgit_function_module.intf.xml
  src/objects/zcl_abapgit_object_auth.clas.abap
  src/objects/zcl_abapgit_object_doma.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_shlp.clas.abap
  src/persist/zcl_abapgit_persistence_db.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/zcl_abapgit_factory.clas.abap
  src/zcl_abapgit_injector.clas.abap
Labels: refactoring

#6584 Refactor Code Inspector and Syntax Check Pages
  src/ui/pages/zcl_abapgit_gui_page_code_insp.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_codi_base.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_syntax.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface, refactoring

#6585 Refactor Diff and Patch Pages
  src/ui/pages/zcl_abapgit_gui_page_diff.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff_base.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff_base.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_patch.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface, refactoring

#6596 Add version constant back to repo settings
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: bug

#6595 Refactor Staging Page
  src/ui/pages/zcl_abapgit_gui_page_code_insp.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
Labels: user interface, refactoring

#6598 Refactor Merge Pages
  src/ui/pages/zcl_abapgit_gui_page_merge.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_res.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_sel.clas.abap
Labels: user interface, refactoring

#6602 Clean-up `zcl_abapgit_gui_chunk_lib`
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
Labels: refactoring

#6604 Replace `TR_TADIR_INTERFACE` with `tadir_delete`
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
Labels: refactoring
