Repository abapGit/abapGit, pull requests merged in 2024-10, with the labels that each got.

#7063 TABU: Display transport requests
  src/cts/zcl_abapgit_cts_api.clas.abap
Labels: user interface

#7062 Show diffs in case of trailing spaces
  src/utils/zcl_abapgit_diff.clas.abap
  src/utils/zcl_abapgit_diff.clas.testclasses.abap
Labels: bug, user interface

#7070 Fix failing AFF unit tests in dev edition 2022
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.testclasses.abap
Labels: testing

#7026 SAJC: Support for Application Job Catalog Entry
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_sajc.clas.abap
  src/objects/aff/zcl_abapgit_object_sajc.clas.xml
Labels: serialization, new feature, aff

#7027 SAJT: Support for Application Job Templates
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_sajt.clas.abap
  src/objects/aff/zcl_abapgit_object_sajt.clas.xml
Labels: serialization, new feature, aff
