Repository abapGit/abapGit, pull requests merged in 2024-07, with the labels that each got.

#6960 TABL: Clear DBINCLEXCL and DBSYSSELx fields
  src/objects/tabl/zcl_abapgit_object_tabl.clas.abap
Labels: serialization

#6962 ENHO: Fix diff in generated comments of class enhancements
  src/objects/enh/zcl_abapgit_object_enho_class.clas.abap
  src/objects/enh/zcl_abapgit_object_enho_class.clas.testclasses.abap
  src/objects/enh/zcl_abapgit_object_enho_class.clas.xml
Labels: serialization

#6961 SXSD: Fix check if BADI exists
  src/objects/zcl_abapgit_object_sxsd.clas.abap
Labels: serialization, bug

#6966 CDBO: Fix missing parameters in `constructor`
  src/objects/aff/zcl_abapgit_object_cdbo.clas.abap
Labels: serialization

#6963 CLIF: Add missing translations for classes and interfaces
  deps/seoclasstx.tabl.xml
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
Labels: serialization

#6969 UIAD: Add support for Launchpad App Descriptor Item
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_uiad.clas.abap
  src/objects/aff/zcl_abapgit_object_uiad.clas.xml
Labels: serialization, new feature

#6974 BGQC: Add support for Background Processing Context
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_bgqc.clas.abap
  src/objects/aff/zcl_abapgit_object_bgqc.clas.xml
Labels: serialization, new feature

#6979 Simplify the JSON2ABAP
  src/objects/texts/zcl_abapgit_properties_file.clas.abap
Labels: aff

#6978 Clear variables when getting `i18n` files
  src/objects/core/zcl_abapgit_filename_logic.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.testclasses.abap
Labels: bug

#6981 Allow staging for empty repositories
  src/repo/zcl_abapgit_repo_online.clas.abap
Labels: bug, repo

#6987 Pass variable to METH
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: serialization, aff

#6951 DSFD: CDS Scalar Function Definition
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_dsfd.clas.abap
  src/objects/aff/zcl_abapgit_object_dsfd.clas.xml
Labels: serialization, new feature

#6953 DRAS: CDS Aspect
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_dras.clas.abap
  src/objects/aff/zcl_abapgit_object_dras.clas.xml
Labels: serialization, new feature

#6993 Fix sap2/sap1 for AFF experimental
  src/objects/texts/zcl_abapgit_properties_file.clas.abap
  src/objects/texts/zcl_abapgit_properties_file.clas.testclasses.abap
  src/objects/texts/zcl_abapgit_properties_file.clas.xml
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
Labels: serialization, aff

#6999 fix: syst_langu does not exist on older releases
  abaplint.json
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
Labels: bug, downport
