Repository abapGit/abapGit, pull requests merged in 2024-03, with the labels that each got.

#6832 bugfix, FORM existence
  src/objects/zcl_abapgit_object_form.clas.abap
Labels: serialization

#6833 unit test page: change colours for runtime
  src/ui/pages/zcl_abapgit_gui_page_runit.clas.abap
Labels: user interface

#6821 Remove duplicate labels from Command Palette.
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: user interface

#6852 IDOC: Fix MOVE_TO_LIT_NOTALLOWED_NODATA
  src/objects/tabl/zcl_abapgit_object_tabl.clas.abap
Labels: serialization, bug

#6853 SICF: Include alternate service name
  src/objects/zcl_abapgit_object_sicf.clas.abap
Labels: serialization, bug

#6851 apack: additional namespace case
  src/apack/zcl_abapgit_apack_reader.clas.abap
Labels: serialization

#6862 Code inspector pages improvements
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/core/zcl_abapgit_html.clas.testclasses.abap
  src/ui/core/zif_abapgit_html.intf.abap
  src/ui/flow/zcl_abapgit_gui_page_flow.clas.abap
  src/ui/lib/zcl_abapgit_gui_page_hoc.clas.abap
  src/ui/lib/zcl_abapgit_html_table.clas.abap
  src/ui/lib/zcl_abapgit_html_table.clas.testclasses.abap
  src/ui/lib/zif_abapgit_html_table.intf.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_code_insp.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_codi_base.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_syntax.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/ui/zabapgit_css_theme_default.w3mi.data.css
Labels: user interface

#6830 AFF: deserialize translation files
  src/objects/aff/zcl_abapgit_json_path.clas.abap
  src/objects/aff/zcl_abapgit_json_path.clas.locals_imp.abap
  src/objects/aff/zcl_abapgit_json_path.clas.testclasses.abap
  src/objects/core/zcl_abapgit_objects_files.clas.abap
  src/objects/texts/zcl_abapgit_properties_file.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
Labels: serialization, aff

#6873 UIPG, UIST: Add support for Launchpad Page and Space Templates
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_uipg.clas.abap
  src/objects/aff/zcl_abapgit_object_uipg.clas.xml
  src/objects/aff/zcl_abapgit_object_uist.clas.abap
  src/objects/aff/zcl_abapgit_object_uist.clas.xml
Labels: serialization, new feature

#6871 Fix Unexpected Functionality for "Maximum Length of Comment" Field
  src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_glob.clas.abap
Labels: user interface

#6869 Refactor: Determine i18n parameters
  src/objects/core/zcl_abapgit_serialize.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/zcl_abapgit_dot_abapgit.clas.abap
Labels: refactoring

#6875 Avoid popup on exit after saving remote settings
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_remo.clas.abap
Labels: user interface

#6870 Fix changing transport type when setting original system
  src/cts/zcl_abapgit_cts_api.clas.abap
  src/cts/zif_abapgit_cts_api.intf.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: bug
