Repository abapGit/abapGit, pull requests merged in 2024-05, with the labels that each got.

#6930 CDBO Object Handler
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_cdbo.clas.abap
  src/objects/aff/zcl_abapgit_object_cdbo.clas.xml
Labels: serialization, new feature

#6918 VIEW: Add authorization group to serialize and deserialize
  src/objects/zcl_abapgit_object_view.clas.abap
Labels: serialization

#6913 Fix Issue Encountered on "Data Config" Page.
  src/ui/pages/zcl_abapgit_gui_page_data.clas.abap
Labels: user interface

#6940 Sync UI theme in dark mode
  src/env/zcl_abapgit_settings.clas.abap
Labels: user interface
