Repository abapGit/abapGit, pull requests merged in 2024-08, with the labels that each got.

#6952 DSFI: CDS Scalar Function Implementation
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_dsfi.clas.abap
  src/objects/aff/zcl_abapgit_object_dsfi.clas.xml
Labels: serialization, new feature

#6997 fix sticky header with browser control warning
  src/ui/zabapgit_css_common.w3mi.data.css
Labels: user interface

#7013 DSFI: Updated object handler to match the latest AFF definition
  src/objects/aff/zcl_abapgit_object_dsfi.clas.abap
Labels: serialization

#7022 [AFF] experimental: Serialize all languages
  src/objects/zcl_abapgit_object_intf.clas.abap
Labels: aff
