Repository abapGit/abapGit, pull requests merged in 2024-04, with the labels that each got.

#6890 ENHO/ENHS: Add missing longtexts
  src/objects/texts/zcl_abapgit_sots_handler.clas.abap
  src/objects/zcl_abapgit_object_enho.clas.abap
  src/objects/zcl_abapgit_object_enhs.clas.abap
Labels: serialization

#6895 Update description of i18n classes/interfaces
  src/objects/texts/zcl_abapgit_i18n_params.clas.xml
  src/objects/texts/zcl_abapgit_po_file.clas.xml
  src/objects/texts/zcl_abapgit_properties_file.clas.xml
  src/objects/texts/zif_abapgit_i18n_file.intf.xml
Labels: serialization

#6892 Refactor: i18n filename logic
  src/objects/core/zcl_abapgit_filename_logic.clas.abap
  src/objects/core/zcl_abapgit_filename_logic.clas.testclasses.abap
  src/objects/core/zcl_abapgit_objects_files.clas.abap
  src/objects/texts/zcl_abapgit_po_file.clas.abap
  src/objects/texts/zcl_abapgit_properties_file.clas.abap
  src/objects/texts/zif_abapgit_i18n_file.intf.abap
Labels: refactoring

#6894 Integrate repo interface into online repo interface
  src/repo/zif_abapgit_repo_online.intf.abap
Labels: repo

#6905 Change message if local packages got lost
  src/repo/zcl_abapgit_repo_status.clas.locals_imp.abap
Labels: serialization, repo

#6906 SOTS: Remove from TADIR selection
  src/objects/core/zcl_abapgit_tadir.clas.abap
Labels: serialization

#6899 Template page
  src/test/zcl_abapgit_gui_page_template.clas.abap
  src/test/zcl_abapgit_gui_page_template.clas.xml
Labels: user interface

#6891 DEVC,NSPC: Serialize software component for add-ons
  src/objects/zcl_abapgit_object_devc.clas.abap
  src/objects/zcl_abapgit_object_nspc.clas.abap
Labels: serialization

#6908 Fix bug in "Object to Files" Page.
  src/ui/pages/zcl_abapgit_gui_page_ex_object.clas.abap
Labels: user interface

#6912 DEVC: Fix "Package must be assigned to the software component LOCAL"
  src/objects/zcl_abapgit_object_devc.clas.abap
Labels: serialization, bug

#6897 Where used page
  src/inspect/zcl_abapgit_where_used_tools.clas.abap
  src/inspect/zcl_abapgit_where_used_tools.clas.xml
  src/ui/core/zcl_abapgit_gui.clas.abap
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/core/zif_abapgit_gui_hotkeys.intf.abap
  src/ui/core/zif_abapgit_html.intf.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/lib/zcl_abapgit_html_table.clas.abap
  src/ui/lib/zcl_abapgit_html_table.clas.testclasses.abap
  src/ui/lib/zcl_abapgit_html_toolbar.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_whereused.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_whereused.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, user interface

#6915 Use bcp47 language code for AFF
  src/objects/aff/zcl_abapgit_json_handler.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
  src/utils/zcl_abapgit_convert.clas.abap
  src/utils/zcl_abapgit_convert.clas.locals_imp.abap
  src/utils/zcl_abapgit_convert.clas.testclasses.abap
Labels: aff
