Repository abapGit/abapGit, pull requests merged in 2024-09, with the labels that each got.

#7036 Fix `CX_SY_ZERODIVIDE` dump in progress bar
  src/ui/progress/zcl_abapgit_progress.clas.abap
Labels: bug

#7038 PROG: Support dynpros with splitter control (2)
  src/objects/zcl_abapgit_objects_program.clas.abap
Labels: serialization

#7039 JOBD: Clear `changedby` field
  src/objects/zcl_abapgit_object_jobd.clas.abap
Labels: serialization

#7040 SFPF: Add syntax highlighting for `xdp` files
  src/syntax/zcl_abapgit_syntax_factory.clas.abap
Labels: user interface

#7041 SFPF: Fix check if object exists
  src/objects/zcl_abapgit_object_sfpf.clas.abap
Labels: serialization

#7037 Add package check when creating repository
  src/repo/zcl_abapgit_repo_srv.clas.abap
Labels: repo

#7045 basic FUGS serialization
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_fugs.clas.abap
  src/objects/zcl_abapgit_object_fugs.clas.xml
  src/objects/zcl_abapgit_objects_program.clas.abap
Labels: serialization

#7031 Comparing GET TIME STAMP and sy-datum and sy-uzeit only works if the user is in UTC
  src/objects/rules/zcl_abapgit_field_rules.clas.testclasses.abap
Labels: testing
