Repository abapGit/abapGit, pull requests merged in 2024-02, with the labels that each got.

#6793 Fix ABAP Language Version Handling for Repository Setting "Any" for AFF Object Types
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/aff/zcl_abapgit_object_common_aff.clas.testclasses.abap
Labels: bug, aff

#6805 DIAL: Prefill package popup
  src/objects/zcl_abapgit_object_dial.clas.abap
Labels: serialization

#6800 Fix AFF unit test on lower releases
  src/objects/aff/zcl_abapgit_object_common_aff.clas.testclasses.abap
Labels: aff, testing

#6803 XSLT: Add check for correct EOL separator
  .editorconfig
  src/objects/zcl_abapgit_object_xslt.clas.abap
  src/utils/zcl_abapgit_utils.clas.abap
Labels: serialization

#6801 Fix unit tests for `ZCL_ABAPGIT_REPO_REQUIREMENTS`
  src/repo/utils/zcl_abapgit_repo_requirements.clas.abap
  src/repo/utils/zcl_abapgit_repo_requirements.clas.testclasses.abap
  test/abap_transpile.json
Labels: bug, testing

#6810 Update the text "Submit Query" in the Command Palette.
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/zabapgit_js_common.w3mi.data.js
Labels: user interface

#6815 Add "ignore sub-packages" option to package export
  src/repo/utils/zcl_abapgit_zip.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_ex_pckage.clas.abap
Labels: new feature, user interface

#6813 Improve form validation of text fields
  src/ui/lib/zcl_abapgit_html_form_utils.clas.abap
  src/ui/lib/zcl_abapgit_html_form_utils.clas.testclasses.abap
Labels: user interface

#6820 Fix Navigation Issue in "Config Display" and "Config Edit" pages.
  src/ui/pages/zcl_abapgit_gui_page_db_entry.clas.abap
Labels: user interface

#6774 Translation for INTF in AFF
  src/objects/aff/zcl_abapgit_json_path.clas.abap
  src/objects/aff/zcl_abapgit_json_path.clas.locals_imp.abap
  src/objects/aff/zcl_abapgit_json_path.clas.testclasses.abap
  src/objects/aff/zcl_abapgit_json_path.clas.xml
  src/objects/texts/zcl_abapgit_properties_file.clas.abap
  src/objects/texts/zcl_abapgit_properties_file.clas.xml
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.locals_imp.abap
  src/objects/zcl_abapgit_objects.clas.testclasses.abap
  test/abap_transpile.json
Labels: serialization

#6806 HTTP connection check and improved error messages
  src/http/zcl_abapgit_http.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.testclasses.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/zabapgit_css_common.w3mi.data.css
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, user interface, repo

#6816 Change transport type when setting original system
  src/cts/zcl_abapgit_cts_api.clas.abap
  src/cts/zif_abapgit_cts_api.intf.abap
  src/objects/zcl_abapgit_objects.clas.abap
Labels: bug
