Repository abapGit/abapGit, pull requests merged in 2024-01, with the labels that each got.

#6724 ZCL_ABAPGIT_REPO, try prefixing the method
  src/repo/zcl_abapgit_repo.clas.abap
Labels: bug, repo

#6733 Do a syntax check before accessing version constant
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_factory.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
  src/objects/oo/zif_abapgit_oo_object_fnc.intf.abap
  src/objects/zcl_abapgit_object_intf.clas.testclasses.abap
  src/repo/utils/zcl_abapgit_version.clas.abap
Labels: repo

#6735 Adjust test in `zcl_abapgit_transport_objects`
  src/cts/zcl_abapgit_transport_objects.clas.testclasses.abap
Labels: testing

#6738 Change all injector classes to `FOR TESTING`
  src/data/zcl_abapgit_data_injector.clas.abap
  src/data/zcl_abapgit_data_injector.clas.xml
  src/git/zcl_abapgit_git_injector.clas.abap
  src/git/zcl_abapgit_git_injector.clas.xml
  src/objects/zcl_abapgit_objects_injector.clas.abap
  src/objects/zcl_abapgit_objects_injector.clas.xml
  src/ui/zcl_abapgit_ui_injector.clas.abap
  src/ui/zcl_abapgit_ui_injector.clas.xml
  src/zcl_abapgit_injector.clas.abap
  src/zcl_abapgit_injector.clas.xml
Labels: testing

#6737 Check class/interface for version is part of repo
  src/repo/utils/zcl_abapgit_version.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: repo

#6741 Rename repository utilities (3)
  src/repo/utils/zcl_abapgit_repo_news.clas.abap
  src/repo/utils/zcl_abapgit_repo_news.clas.testclasses.abap
  src/repo/utils/zcl_abapgit_repo_news.clas.xml
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: refactoring, repo

#6739 Rename repository utilities (1)
  deps/cvers.tabl.xml
  deps/cvers_ref.tabl.xml
  src/repo/utils/zcl_abapgit_repo_requirements.clas.abap
  src/repo/utils/zcl_abapgit_repo_requirements.clas.testclasses.abap
  src/repo/utils/zcl_abapgit_repo_requirements.clas.xml
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  test/abap_transpile.json
Labels: refactoring, repo

#6740 Rename repository utilities (2)
  src/repo/utils/zcl_abapgit_repo_item_state.clas.abap
  src/repo/utils/zcl_abapgit_repo_item_state.clas.testclasses.abap
  src/repo/utils/zcl_abapgit_repo_item_state.clas.xml
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: refactoring, repo

#6742 Refactor ZCL_ABAPGIT_OO_FACTORY
  src/objects/oo/zcl_abapgit_oo_base.clas.abap
  src/objects/oo/zcl_abapgit_oo_class.clas.abap
  src/objects/oo/zcl_abapgit_oo_factory.clas.abap
  src/objects/oo/zcl_abapgit_oo_interface.clas.abap
  src/objects/zcl_abapgit_object_clas.clas.abap
  src/objects/zcl_abapgit_object_intf.clas.abap
  src/repo/utils/zcl_abapgit_version.clas.abap
Labels: refactoring

#6744 Allow disabling of GUI
  src/ui/lib/zcl_abapgit_html_form_utils.clas.testclasses.abap
  src/ui/pages/zcl_abapgit_gui_page_sett_remo.clas.testclasses.abap
  src/ui/zcl_abapgit_frontend_no_gui.clas.abap
  src/ui/zcl_abapgit_frontend_no_gui.clas.xml
  src/ui/zcl_abapgit_ui_factory.clas.abap
Labels: user interface

#6749 downport: fix syntax error in `zcl_abapgit_object_tabl_ddl`
  src/objects/tabl/zcl_abapgit_object_tabl_ddl.clas.abap
Labels: downport

#6745 DDLS: deletes remaining TADIR entry during delete
  src/objects/zcl_abapgit_object_ddls.clas.abap
Labels: serialization

#6751 Downport zcl_abapgit_object_tabl_ddl
  src/objects/tabl/zcl_abapgit_object_tabl_ddl.clas.abap
Labels: downport

#6753 Fix: Cannot change repo settings without version constant
  src/ui/pages/zcl_abapgit_gui_page_sett_repo.clas.abap
Labels: bug

#6752 Create package popup: Fix prefill package name
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/ui/zcl_abapgit_popups.clas.abap
  src/ui/zif_abapgit_popups.intf.abap
Labels: bug

#6767 New abapGit Handler for Object Type DRTY
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_drty.clas.abap
  src/objects/aff/zcl_abapgit_object_drty.clas.xml
Labels: serialization, new feature, aff

#6759 Distinguish between "Global Settings" and "Repository Settings"
  src/ui/lib/zcl_abapgit_gui_buttons.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
Labels: user interface
