Repository abapGit/abapGit, pull requests merged in 2024-06, with the labels that each got.

#6920 Set Default Git User Details
  src/env/zcl_abapgit_settings.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_pers.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: user interface

#6941 Small performance improvement in folder logic
  src/objects/core/zcl_abapgit_folder_logic.clas.abap
  src/objects/core/zcl_abapgit_folder_logic.clas.locals_imp.abap
Labels: serialization, performance

#6944 Remove duplicate clipboad action
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/zabapgit_js_common.w3mi.data.js
  src/zif_abapgit_definitions.intf.abap
Labels: refactoring

#6945 Fix folder logic buffer
  src/objects/core/zcl_abapgit_folder_logic.clas.abap
Labels: bug

#6942 Exclude files from remote
  src/persist/zif_abapgit_persistence.intf.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_locl.clas.abap
Labels: new feature
