Repository abapGit/abapGit, pull requests merged in 2025-02, with the labels that each got.

#7140 Execute WDCC after import method
  src/objects/zcl_abapgit_object_wdcc.clas.abap
Labels: serialization

#7143 Added support for COTA - Communication Target
  src/objects/aff/zcl_abapgit_aff_registry.clas.abap
  src/objects/aff/zcl_abapgit_object_cota.clas.abap
  src/objects/aff/zcl_abapgit_object_cota.clas.xml
Labels: serialization, new feature

#7132 Exit: Enhance any toolbar
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zif_abapgit_exit.intf.abap
  src/objects/core/zcl_abapgit_serialize.clas.testclasses.abap
  src/test/zcl_abapgit_gui_page_template.clas.abap
  src/ui/flow/zcl_abapgit_gui_page_flow.clas.abap
  src/ui/lib/zcl_abapgit_gui_menus.clas.abap
  src/ui/lib/zcl_abapgit_gui_page.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_codi_base.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_runit.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_whereused.clas.abap
  src/ui/pages/db/zcl_abapgit_gui_page_db.clas.abap
  src/ui/pages/db/zcl_abapgit_gui_page_db_entry.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_data.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff_base.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_res.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_pull.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tutorial.clas.abap
Labels: new feature, exit

#7147 Filter nonexistent FMs from inconsistent FUGR
  src/objects/zcl_abapgit_object_fugr.clas.abap
Labels: serialization

#7146 Fix dump in non-Unicode systems
  src/ui/core/zcl_abapgit_gui_event.clas.abap
Labels: bug

#7152 Fix version badge
  README.md
Labels: documentation

#7153 Fix highlight of CR, LF, CRLF
  src/syntax/zcl_abapgit_syntax_highlighter.clas.abap
Labels: user interface

#7149 Fix http service githandler in older releases
  src/objects/zcl_abapgit_object_http.clas.abap
Labels: serialization
