Repository abapGit/abapGit, pull requests merged in 2025-07, with the labels that each got.

#7322 Refactor: move type to gui layer
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.locals_imp.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: user interface, refactoring

#7334 SSFO: bugfix sorting
  src/objects/zcl_abapgit_object_ssfo.clas.abap
  src/objects/zcl_abapgit_object_ssfo.clas.testclasses.abap
  src/objects/zcl_abapgit_object_ssfo.clas.xml
Labels: serialization

#7328 Improve performance of background push
  src/background/zcl_abapgit_background_push_au.clas.abap
Labels: performance, background
