Repository abapGit/abapGit, pull requests merged in 2025-08, with the labels that each got.

#7365 Fix navigation after error calling a new page
  src/ui/core/zcl_abapgit_gui.clas.abap
  src/ui/lib/zcl_abapgit_gui_picklist.clas.abap
  src/ui/lib/zcl_abapgit_html_form.clas.abap
  src/ui/pages/diff/zcl_abapgit_gui_page_diff_base.clas.abap
  src/ui/pages/diff/zcl_abapgit_gui_page_patch.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#7346 TABU: Add application table entries to transport
  src/data/zcl_abapgit_data_deserializer.clas.abap
  src/data/zcl_abapgit_data_utils.clas.abap
Labels: data config

#7374 TABL: clearing some `DD36M` fields
  src/objects/tabl/zcl_abapgit_object_tabl.clas.abap
Labels: serialization
