Repository abapGit/abapGit, pull requests merged in 2025-01, with the labels that each got.

#7100 Object Handler of type HTTP
  src/objects/core/zcl_abapgit_file_deserialize.clas.abap
  src/objects/zcl_abapgit_object_http.clas.abap
  src/objects/zcl_abapgit_object_http.clas.xml
Labels: serialization, new feature, ci

#7124 Fix dump in language mapping
  src/utils/zcl_abapgit_convert.clas.locals_imp.abap
Labels: bug

#7123 Refactor `zcx_abapgit_exception`
  src/zcx_abapgit_exception.clas.abap
  src/zcx_abapgit_exception.clas.testclasses.abap
Labels: refactoring

#7129 CHDO: Refactor logic for generated objects
  deps/tcdrs.tabl.xml
  src/objects/tabl/zcl_abapgit_object_tabl.clas.abap
  src/objects/zcl_abapgit_object_fugr.clas.abap
  src/objects/zcl_abapgit_object_prog.clas.abap
  src/repo/filter/zcl_abapgit_repo_filter.clas.abap
Labels: serialization

#7126 Patch: fix 'invalid filename' error if filename is empty
  src/ui/pages/zcl_abapgit_gui_page_patch.clas.abap
Labels: bug
