Repository abapGit/abapGit, pull requests merged in 2025-04, with the labels that each got.

#7182 Remove http-agent from factory
  src/git_platform/zcl_abapgit_pr_enumerator.clas.abap
  src/zcl_abapgit_factory.clas.abap
  src/zcl_abapgit_injector.clas.abap
  test/src/zcl_abapgit_gitea.clas.abap
Labels: refactoring

#7178 Feature: Objects locked in multiple requests
  src/cts/zcl_abapgit_cts_api.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature, repo

#7186 Add some icons
  src/ui/zabapgit_icon_font.w3mi.data.woff
  src/ui/zabapgit_icon_font_css.w3mi.data.css
Labels: user interface

#7188 Debug info: Fix exit list in standalone
  src/ui/pages/zcl_abapgit_gui_page_debuginfo.clas.abap
Labels: exit

#7190 Add style option for HTML rendering
  src/ui/core/zcl_abapgit_html.clas.abap
  src/ui/core/zif_abapgit_html.intf.abap
Labels: user interface

#7187 Fix checking support of object types (exit)
  src/exits/zif_abapgit_exit.intf.abap
  src/objects/zcl_abapgit_objects.clas.abap
Labels: exit

#7200 Repo Overview: Add sort by online/offline repo
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
Labels: user interface

#7189 Repo Refactoring: Use interfaces instead of classes
  src/background/zcl_abapgit_background.clas.abap
  src/background/zcl_abapgit_background_pull.clas.abap
  src/background/zcl_abapgit_background_push_au.clas.abap
  src/background/zcl_abapgit_background_push_fi.clas.abap
  src/background/zif_abapgit_background.intf.abap
  src/cts/zcl_abapgit_transport.clas.abap
  src/cts/zcl_abapgit_transport_2_branch.clas.abap
  src/data/zcl_abapgit_data_deserializer.clas.abap
  src/data/zif_abapgit_data_deserializer.intf.abap
  src/exits/zcl_abapgit_exit.clas.abap
  src/exits/zif_abapgit_exit.intf.abap
  src/git_platform/zcl_abapgit_git_url.clas.abap
  src/objects/core/zcl_abapgit_file_deserialize.clas.abap
  src/objects/core/zcl_abapgit_objects_check.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/repo/stage/zcl_abapgit_merge.clas.abap
  src/repo/stage/zcl_abapgit_stage_logic.clas.abap
  src/repo/stage/zif_abapgit_merge.intf.abap
  src/repo/stage/zif_abapgit_stage_logic.intf.abap
  src/repo/utils/zcl_abapgit_repo_news.clas.abap
  src/repo/zcl_abapgit_repo.clas.abap
  src/repo/zcl_abapgit_repo.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_checksums.clas.testclasses.abap
  src/repo/zcl_abapgit_repo_content_list.clas.abap
  src/repo/zcl_abapgit_repo_online.clas.abap
  src/repo/zcl_abapgit_repo_srv.clas.abap
  src/repo/zif_abapgit_repo.intf.abap
  src/ui/flow/zcl_abapgit_flow_logic.clas.abap
  src/ui/flow/zcl_abapgit_gui_page_flow.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.testclasses.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_code_insp.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_codi_base.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_runit.clas.abap
  src/ui/pages/codi/zcl_abapgit_gui_page_syntax.clas.abap
  src/ui/pages/dlg/zcl_abapgit_gui_page_addofflin.clas.abap
  src/ui/pages/dlg/zcl_abapgit_gui_page_addonline.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_bckg.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_info.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_locl.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_remo.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_remo.clas.testclasses.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_repo.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_chg_pckg.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_commit.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_data.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff_base.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_res.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_merge_sel.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_patch.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_pull.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_tags.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/routing/zcl_abapgit_services_git.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.abap
  src/zabapgit_forms.prog.abap
Labels: refactoring, repo

#7205 Fix `zcl_abapgit_serializer` test
  src/objects/core/zcl_abapgit_serialize.clas.abap
Labels: testing

#7215 New error handling for not supported object types
  src/objects/aff/zcl_abapgit_object_common_aff.clas.abap
  src/objects/aff/zcl_abapgit_object_smbc.clas.abap
  src/objects/aff/zcl_abapgit_object_uiad.clas.abap
  src/objects/aff/zcl_abapgit_object_uipg.clas.abap
  src/objects/aff/zcl_abapgit_object_uist.clas.abap
  src/objects/zcl_abapgit_object_aifc.clas.abap
  src/objects/zcl_abapgit_object_amsd.clas.abap
  src/objects/zcl_abapgit_object_apis.clas.abap
  src/objects/zcl_abapgit_object_bdef.clas.abap
  src/objects/zcl_abapgit_object_cmpt.clas.abap
  src/objects/zcl_abapgit_object_dcls.clas.abap
  src/objects/zcl_abapgit_object_ddls.clas.abap
  src/objects/zcl_abapgit_object_ddlx.clas.abap
  src/objects/zcl_abapgit_object_drul.clas.abap
  src/objects/zcl_abapgit_object_dtdc.clas.abap
  src/objects/zcl_abapgit_object_ftgl.clas.abap
  src/objects/zcl_abapgit_object_http.clas.abap
  src/objects/zcl_abapgit_object_iobj.clas.abap
  src/objects/zcl_abapgit_object_jobd.clas.abap
  src/objects/zcl_abapgit_object_odso.clas.abap
  src/objects/zcl_abapgit_object_samc.clas.abap
  src/objects/zcl_abapgit_object_sapc.clas.abap
  src/objects/zcl_abapgit_object_saxx_super.clas.abap
  src/objects/zcl_abapgit_object_sktd.clas.abap
  src/objects/zcl_abapgit_object_smtg.clas.abap
  src/objects/zcl_abapgit_object_sod1.clas.abap
  src/objects/zcl_abapgit_object_sod2.clas.abap
  src/objects/zcl_abapgit_object_sqsc.clas.abap
  src/objects/zcl_abapgit_object_srfc.clas.abap
  src/objects/zcl_abapgit_object_srvb.clas.abap
  src/objects/zcl_abapgit_object_srvd.clas.abap
  src/objects/zcl_abapgit_object_sush.clas.abap
  src/objects/zcl_abapgit_object_wdcc.clas.abap
  src/objects/zcl_abapgit_objects.clas.abap
  src/objects/zcl_abapgit_objects_bridge.clas.abap
  src/objects/zcl_abapgit_objects_generic.clas.abap
  src/zcx_abapgit_type_not_supported.clas.abap
  src/zcx_abapgit_type_not_supported.clas.xml
Labels: refactoring

#7218 Add support for ABAP Language Version for generic
  src/objects/rules/zcl_abapgit_field_rules.clas.abap
  src/objects/rules/zcl_abapgit_field_rules.clas.testclasses.abap
  src/objects/rules/zif_abapgit_field_rules.intf.abap
  src/objects/zcl_abapgit_object_g4ba.clas.abap
  src/objects/zcl_abapgit_object_g4bs.clas.abap
  src/objects/zcl_abapgit_object_iwmo.clas.abap
  src/objects/zcl_abapgit_object_iwom.clas.abap
  src/objects/zcl_abapgit_object_iwsg.clas.abap
  src/objects/zcl_abapgit_object_iwsv.clas.abap
  src/objects/zcl_abapgit_object_iwvb.clas.abap
Labels: serialization

#7222 SCVI: Fix unstable diff when `shdsvfvci` or `shdguixt` are not initial
  src/objects/zcl_abapgit_object_scvi.clas.abap
Labels: serialization

#7224 refactor DDLS + DDLX + DCLS
  src/objects/zcl_abapgit_object_dcls.clas.abap
  src/objects/zcl_abapgit_object_ddls.clas.abap
  src/objects/zcl_abapgit_object_ddlx.clas.abap
Labels: refactoring

#7227 FDT0: Remove comparator
  src/objects/zcl_abapgit_object_fdt0.clas.abap
Labels: serialization

#7229 Refactor: Persistence factory
  src/background/zcl_abapgit_background.clas.abap
  src/objects/zcl_abapgit_object_devc.clas.abap
  src/persist/zcl_abapgit_persist_background.clas.abap
  src/persist/zcl_abapgit_persist_factory.clas.abap
  src/persist/zcl_abapgit_persist_injector.clas.abap
  src/persist/zcl_abapgit_persist_packages.clas.abap
  src/persist/zcl_abapgit_persist_packages.clas.testclasses.abap
  src/persist/zcl_abapgit_persistence_repo.clas.abap
  src/persist/zcl_abapgit_persistence_user.clas.abap
  src/persist/zif_abapgit_persist_background.intf.abap
  src/persist/zif_abapgit_persist_background.intf.xml
  src/persist/zif_abapgit_persist_packages.intf.abap
  src/persist/zif_abapgit_persist_packages.intf.xml
  src/ui/lib/zcl_abapgit_gui_chunk_lib.clas.abap
  src/ui/pages/sett/zcl_abapgit_gui_page_sett_bckg.clas.abap
Labels: refactoring
