Repository abapGit/abapGit, pull requests merged in 2025-03, with the labels that each got.

#7150 Staging issue when folder name is in uppercase
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/utils/zcl_abapgit_path.clas.abap
Labels: repo

#7155 Refactor: Decouple staging logic from factory
  src/background/zcl_abapgit_background_push_au.clas.abap
  src/background/zcl_abapgit_background_push_fi.clas.abap
  src/cts/zcl_abapgit_transport_2_branch.clas.abap
  src/repo/stage/zcl_abapgit_stage_logic.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_stage.clas.abap
  src/zcl_abapgit_factory.clas.abap
  src/zcl_abapgit_injector.clas.abap
Labels: refactoring, repo

#7131 Feature: Change Repo Package
  deps/if_package.intf.abap
  src/objects/core/zcl_abapgit_dependencies.clas.testclasses.abap
  src/objects/core/zcl_abapgit_folder_logic.clas.testclasses.abap
  src/objects/sap/zcl_abapgit_sap_package.clas.abap
  src/objects/sap/zif_abapgit_sap_package.intf.abap
  src/repo/zcl_abapgit_repo_status.clas.testclasses.abap
  src/ui/pages/zcl_abapgit_gui_page_chg_pckg.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_chg_pckg.clas.xml
  src/ui/pages/zcl_abapgit_gui_page_repo_over.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_repo_view.clas.abap
  src/ui/routing/zcl_abapgit_gui_router.clas.abap
  src/ui/routing/zcl_abapgit_services_repo.clas.testclasses.abap
  src/zif_abapgit_definitions.intf.abap
Labels: new feature

#7174 Add "Back" button to diff and where-used pages
  src/ui/pages/codi/zcl_abapgit_gui_page_whereused.clas.abap
  src/ui/pages/zcl_abapgit_gui_page_diff_base.clas.abap
Labels: user interface
